### ISSUE TITLE
convert readable code into none readable... may explain please

### ISSUE THREAD

**Issue by ImmoWetzel** [PyCQA/pycodestyle#1000]
HI,

we use black in the company to format the python code for some small internal tools. But nobody could explain why black converts a readable code into non readable.. There is for sure an idea behind this.
Which ?

example:
```
    parser.add_argument("-o", "--output_dir",   default=None, help="fixed folder of the BaseConfig log output and modified XML file; or automatic /tmp/ ")
    parser.add_argument("-a", "--arg_file",     default=None, help="Robot Project argument file (when given this replaces all other arguments) ")
    parser.add_argument("-e", "--debug",        default=None, help="debug level < *INFO* | DEBUG > ")

```
the extra spaces makes it more readable and faster readable and verify but black removes the extra spaces.

example:
an dictionary is filled with defaults very self explaining 
```
            ....
            'propagate': True
            },
            'plain': {
                'handlers': ['plain'],
                'level': "DEBUG",
                'propagate': True
            }
        }
    })

```
but black compresses many of these helpful structures. Why ?

**Comment by asottile** [comment]
black's issue tracker is here: https://github.com/psf/black
