### ISSUE TITLE
noqa is ignored with type annotations

### ISSUE THREAD

**Issue by spaceone** [PyCQA/pycodestyle#1014]
`search = lambda x: True  # type: ignore # noqa: E731`
causes:
`test_flake8_e731.py:1:1: E731 do not assign a lambda expression, use a def`

→ the `noqa` should be evaluated

**Comment by asottile** [comment]
E731 is not among the codes that can be disabled with `# noqa` in pycodestyle: https://github.com/PyCQA/pycodestyle/blob/master/docs/intro.rst

**Comment by spaceone** [comment]
Hm, there is only one line about noqa: `(^) These checks can be disabled at the line level using the # noqa special comment.`
But this is not a reason to just close this issue when it's a use case.

**Comment by sigmavirus24** [comment]
No, the tool genuinely doesn't allow certain violations to be ignored inline with `# noqa`. That's a valid reason to close this as  there's no bug here

**Comment by sigmavirus24** [comment]
Also, I think even if E731 did support `# noqa`, you're using Flake8 syntax which isn't supported in pycodestyle directly
