### ISSUE TITLE
Imports after adding to `sys.path`  triggers E402

### ISSUE THREAD

**Issue by Marsfan** [PyCQA/pycodestyle#1026]
As an example, consider the following snippet from a  Sphinx _conf.py_ file where `module` is located one folder up from _conf.py_:

```python
import os
import sys

sys.path.insert(0, os.path.abspath(".."))
import module.submodule
```

`pycodestyle` complains that the module level imports are not at the top of the file. 
This is especially significant as some formatters (specifically [autopep8](https://github.com/hhatto/autopep8)) use pycodestyle as  their backend, and "fixing" the formatting will result in the code no longer functioning. 

This is similar to the dunder issue that was fixed in #613, except it deals with adding to the path instead of including dunder variables, thus the fix will likely be similar .

**Comment by asottile** [comment]
this is intentional -- `sys.path.insert` **is a hack**
