### ISSUE TITLE
`E704` conflicts with black code style in `.pyi` files

### ISSUE THREAD

**Issue by DetachHead** [PyCQA/pycodestyle#1036]
```py
def foo() -> None: ...
```
```
E704 multiple statements on one line (def)
```

black puts the `...` on the same line in `.pyi` files

**Comment by DetachHead** [comment]
#957

**Comment by sigmavirus24** [comment]
As said in #959 

> is this needed? E704 is disabled by default

Also that thread has ways of making sure you don't see E704 while ignoring the errors you want to ignore.

Put another way: "Are you deliberately enabling E704?"

**Comment by ezyang** [comment]
This is worse now because latest version of black now applies this to .py files, not only .pyi files

**Comment by DetachHead** [comment]
i suggest using ruff instead of flake8/black. ruff has both a linter and formatter that are designed to be used together so you don't run into issues like this as often
