### ISSUE TITLE
Unpaired Bidi Control Character Detection

### ISSUE THREAD

**Issue by GBeauregard** [PyCQA/pycodestyle#1037]
Unpaired bidi control characters can lead to security problems in python source code, as demonstrated at https://trojansource.codes/

Although some languages (rust) and compilers (clang, gcc) are being modified to reject unpaired bidi characters, the python security team rejected this and the discussion is that this should be implemented in python linters instead: https://mail.python.org/archives/list/python-dev@python.org/thread/6DBJJRQHA2SP5Q27MOMDSTCOXMW7ITNR/

Can a new feature be implemented to detect unpaired bidi control characters?

**Comment by sigmavirus24** [comment]
This is a style linter not a security linter. Please request this on bandit

**Comment by GBeauregard** [comment]
I'm not sure Bandit is a good fit since it claims to work on the AST level and the attack occurs at the style level, but I'll open there too. Thanks for the quick response as well; I'm hopeful CPython security team will reconsider rejecting this at the compiler.
