### ISSUE TITLE
regression with `if parent_type(LL[0]) == syms.test:`

### ISSUE THREAD

**Issue by asottile** [PyCQA/pycodestyle#1048]
looks like this regressed as part of #1041

CC @asfaltboy

here's some code, extracted from black:

```python
if parent_type(LL[0]) == syms.test:
    pass
```

before it raised no errors, now it raises:

```console
$ python3 /tmp/pycodestyle/pycodestyle.py t.py 
t.py:1:11: E721 do not compare types, use 'isinstance()'
```

**Comment by asfaltboy** [comment]
Sorry for the silly mistake, and thanks for the quick fix @asottile 🙇
