### ISSUE TITLE
New lint: calling lambda expression directly

### ISSUE THREAD

**Issue by jpy-git** [PyCQA/pycodestyle#1060]
This is similar to `E731` which flags the assignment of a lambda expression (e.g. `a = lambda x: x`)

I would like to flag situations in which a lambda function is called directly rather than defining it as a function and then calling it
```python
(lambda x: x)('hello world')
```
should instead be
```python
def func(x):
    return x

func("hello world")
```

**Comment by asottile** [comment]
also I'd argue that both of those are poor ways to write that code -- there's no reason to write a lambda/function which is immediately executed only once -- just put the expression inline

**Comment by jpy-git** [comment]
> just put the expression inline

Very good point, thanks both 👍
