### ISSUE TITLE
E501: Documented exception not honored

### ISSUE THREAD

**Issue by vastbluesky** [PyCQA/pycodestyle#1064]
According to the [flake8 documentation for `max-line-length`][1], lines in the following format should be exempt from the maximum length rule:

```python
url = (
    'https://...'
)
```

However, both pycodestyle and flake8 raise E501 warnings for long lines in exactly that format.

Steps to reproduce: I saved the following to a file named `url.py`

```python
url = (
    'https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-max-line-length'
)

```

Then ran

```shellSession
> flake8 url.py
url.py:2:80: E501 line too long (91 > 79 characters)
> pycodestyle url.py
url.py:2:80: E501 line too long (91 > 79 characters)
> flake8 --version
4.0.1 (mccabe: 0.6.1, pycodestyle: 2.8.0, pyflakes: 2.4.0) CPython 3.10.4 on Windows
```

I would be happy to raise this issue in PyCQA/flake8 instead if that would be more appropriate.

[1]: https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-max-line-length

**Comment by asottile** [comment]
this is probably just a documentation bug -- I'll remove the section from the flake8 docs
