### ISSUE TITLE
Support pathlib objects in StyleGuide.input_dir()

### ISSUE THREAD

**Issue by utkonos** [PyCQA/pycodestyle#1069]
## Issue
The `check_files()` method handles `pathlib` objects just fine, but the `input_dir()` method raises an `AttributeError`.
## Feature Request
Handle `pathlib` objects in `input_dir()` method.
## Error
```
Traceback (most recent call last):
  File "/Users/username/Desktop/project/tests/test_linters.py", line 40, in test_pycodestyle
    result = self.style.input_dir(self.package_dir)
  File "/Library/Python/3.10/lib/python/site-packages/pycodestyle.py", line 2492, in input_dir
    dirname = dirname.rstrip('/')
AttributeError: 'PosixPath' object has no attribute 'rstrip'
```
## Workaround
The workaround is to wrap the `pathlib` object in the `str()` built-in function.
```
result = self.style.input_dir(str(self.package_dir))
```

**Comment by sigmavirus24** [comment]
I'd rather not bother. It doesn't improve the tool
