### ISSUE TITLE
Update the default for max-line-length

### ISSUE THREAD

**Issue by majurgens** [PyCQA/pycodestyle#1076]
I'm suggesting that the default value of 79 for this is now too small. I appreciate that it is a parameter driven value but I have come across projects that just use the default, maybe because they think that it is optimal. I'd suggest that the default value should just be increased. Possibly to something like 200 characters.

I'll expand on the reasoning for changing the default value.

The formatting requirement for lines less that 79 characters brings me back to the 1980s where I used to use green screen terminals that actually were limited to 80 characters. This formatting requirement seems unrealistic and actually makes the code less readable. I don't know about you but even if I have, what is a small screen today at 1920x1080 I can easily fit 160 characters on a line that only uses maybe 2/3 of the width of my screen. What width monitor do you have? There is an increasing number of 4k monitors with a width of more than 3000 pixels. Many people I know have upgraded to wide-screen monitors. I doubt you would find many developers with less than 1920x1080.

On any monitor today, vertical space is more of a premium than horizontal space. most monitors are wider than they are high. For example, 1920x1080 is a typical aspect ratio. An artificially constrained, uses that more limited resource (width) and forces people to scroll up and down to read code when scrolling would not otherwise be required. If you have to scroll to read a code block, it makes the code harder to understand and is more of a cognitive load on people, potentially leading to mistakes, or misunderstandings.

There are several other formatting requirements, that clash with this width requirement, for example 4 space indentation, spaces after commas and so on. These other requirements make lines longer and hence increase the chance of breaking the default line length.

For example, this line, after adding all the other spaces and 4-space indentation, pushes the line to 80 characters - only one character over. Would this be more readable by splitting it?
`    config_file = os.getenv('WMIC_SERVER_CONFIG', str(working_dir) + '/wmic_server.yaml')

The PEP8 definition calls this line length a suggestion - "PEP 8 suggests lines should be limited to 79 characters.". The max of 79 characters seems a bit archaic and I think should be modernised taking into account advances is hardware since this limit was first conceived.

Here are a couple of examples that actually makes the code (in this case a comment) harder to read and use

The comment is:
# PYTHONPATH=/opt/nagios/bin/plugins/aiowmi FLASK_ENV=development WMIC_SERVER_DEBUG=1 python /opt/nagios/bin/plugins/aiowmi/contrib/wmic_server/wmic_server.py
which is intended to be a copy and paste, single line command to run the server. Splitting this up would appear to render this useless. In reality this line, when used as a command line will be longer than 79 characters

Another example I just found was this line is 89 characters instead of 79:
sys.stdout = io.TextIOWrapper(open(sys.stdout.fileno(), 'wb', 0), write_through=True)

Splitting that line also seems unnecessary.

The good thing, is that, since this is parameterised, even if the default is increased, anyone wanting to use the old value still can.
Additionally, even if the default is increased, all existing code is still (presumably) compliant.

Thoughts?

I could probably find the code where 79 is configured and submit a PR if needed.

**Comment by asottile** [comment]
you're free to configure whatever value you'd like via the `max-line-length` setting to your preference.  or to turn off the check entirely via `extend-ignore` / `ignore`

**Comment by majurgens** [comment]
It is somewhat disappointing to have my carefully thought out reasoning simply dismissed without any apparent thought or discussion using information that I already acknowledged in my opening paragraph.

How wide is your screen? I am currently on a screen that presents about 1700 pixels and I can easily fit 240 characters on a line. A limit of 79 characters per line is about 30% of my current small screen. Forcing people to code to a width that is 20-40% of their available screen width is less than optimal for user experience.

This is a situation where standards have not kept pace with technology. Imagine a scenario where there was an industry-wide standard to only use single-threading just because it was a standard.

**Comment by asottile** [comment]
as I said above, the tool is not forcing anyone to do anything -- you're free to deviate from the suggestions of PEP8 and there are two ways you can configure your preference
