### ISSUE TITLE
E203 and E231 generated for "walrus" operator

### ISSUE THREAD

**Issue by darrincedwards** [PyCQA/pycodestyle#1079]
This may be a duplicate of [this issue](https://github.com/PyCQA/pycodestyle/issues/373), but that seemed focused on list slices.

For code that attempts to use the python 3.8 ["assisnment expression"](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions), also known as the "walrus" operator, I get the following (running flake8 3.7.9 with pycodestyle 2.5.0):

`darrin@cornelia ~> flake8 (echo 'actual_float = float(txt_float := "3.14")' | psub)`
`"pyflakes" failed during execution due to "'FlakesChecker' object has no attribute 'NAMEDEXPR'"`
`Run flake8 with greater verbosity to see more details`
`/tmp/.psub.Aza7RP6fl1:1:31: E203 whitespace before ':'`
`/tmp/.psub.Aza7RP6fl1:1:32: E231 missing whitespace after ':'`

Attempting to add / remove space in and around the `:=` operator just generates different errors (and many of those aren't valid python anyway).

**Comment by FichteFoll** [comment]
You should update to a version that supports assignment expressions, i.e. 2.6.0 or higher, released 2 years ago.

https://github.com/PyCQA/pycodestyle/blob/59f2e31d0f032ffccb0ad64761f58758a844796d/CHANGES.txt#L60

**Comment by asottile** [comment]
general advice for open source: always check the newest released version and the latest revision of the primary branch -- 2.5.0 was released a full year before python 3.8 was released
