### ISSUE TITLE
Suggestion: prohibit blank lines between symbol definitions and their docstrings

### ISSUE THREAD

**Issue by PeterJCLaw** [PyCQA/pycodestyle#1099]
For example:
```python
class Foo:

    "bad docstring"
```
``` python
def bar():

    "bad docstring"
```
This would match the fixing which `autopep8` provides.
Currently `autopep8` handles this as part of `E303`, which seems about right though I could also see this as new `E30x`.

**Comment by asottile** [comment]
you're looking for https://pypi.org/project/pydocstyle/
