### ISSUE TITLE
E275: Warning if keyword is at the end of a line

### ISSUE THREAD

**Issue by jnsebgosselin** [PyCQA/pycodestyle#1102]
I am using `pycodestyle 2.9.1` in Spyder and the following code yield a E275 warning on lines 3, 7, and 9. I am not sure if this is as expected.

```Python
try:
    xabs = [
        abs(x) for x in
        [1, -2, 3, -4]
        ]
except Exception:
    return
else:
    pass
```

![image](https://user-images.githubusercontent.com/10170372/191840558-ce8d7b45-0305-4b3f-b6e2-2513994f3474.png)

**Comment by asottile** [comment]
I can't reproduce -- can you attach the exact file?

**Comment by jnsebgosselin** [comment]
Sure, there you go:

[warn_275_pycodestyle.txt](https://github.com/PyCQA/pycodestyle/files/9629206/warn_275_pycodestyle.txt)

There is no such warnings when using `pycodestyle 2.8.0`, which is as expected I guess.

**Comment by asottile** [comment]
I can't reproduce -- it's probably something spyder is doing incorrectly:

```console
$ pycodestyle --version
2.9.1
$ pycodestyle warn_275_pycodestyle.py 
$
```

**Comment by jnsebgosselin** [comment]
You are correct. I cannot reproduce when evaluating the file with :

```
import pycodestyle
sut = pycodestyle.StyleGuide()
results = sut.input_file(filename="warn_275_pycodestyle.py")
print(results)
```

I will report this issue in the Spyder repo directly. Thanks for the quick replies!
