### ISSUE TITLE
You keep publishing wheels for Python 2, but they are incompatible

### ISSUE THREAD

**Issue by wvxvw** [PyCQA/pycodestyle#1112]
For instance, the function `extraneous_whitespace` contains f-string syntax, but the wheel is published under `pycodestyle-2.9.1-py2.py3-none-any.whl` name. Notice the `py2` in the name: it means it's compatible with Python 2.

**Comment by asottile** [comment]
the filename isn't what decides the installability, that's the `python_requires` setting

the py2 comes from the "universal" setting which means it's purelib (and I use that to track purelib things)

**Comment by wvxvw** [comment]
Sorry. You are wrong. The file name is what decides whether a package is available for installing. At the time `pip` or similar tools decide what to install, these tools don't even have any knowledge of the contents of the archive. You simply didn't name your archives correctly.

`python_requires` is irrelevant in this context. It is only used when resolving *dependencies* (by reading the `METADATA` file in the Wheel). This cannot possibly be done for the wheel being installed, it can only be done for dependencies.

**Comment by wvxvw** [comment]
As an aside: don't close issues before you get an OK from the person opening them. You come out as a jerk if you do that.

**Comment by asottile** [comment]
if you don't believe me, try view-source on https://pypi.org/simple/pycodestyle
