### ISSUE TITLE
Settings are ignored if there are comments on that same line.

### ISSUE THREAD

**Issue by WhyNotHugo** [PyCQA/pycodestyle#1115]
This work:

```dosini
[pycodestyle]
ignore = W503, E501
```

But this does not:

```dosini
[pycodestyle]
ignore =
  W503,  # Line jump before binary operator.
  E501,  # We rely on bugbear's B950 for this.
```

This last format works with `[flake8]`, but it seems that using `[pycodestyle]` is the more compatible approach with different tools.

**Comment by asottile** [comment]
can you elaborate on "does not work" -- it's unclear from your issue

**Comment by asottile** [comment]
(note also that your syntax doesn't work for flake8 either -- it will be an error in the future) -- see "inline comments" here: https://flake8.pycqa.org/en/latest/user/configuration.html (you're silently ignoring B950 for example)

since neither is supported in either tool I believe this is wontfix

**Comment by WhyNotHugo** [comment]
> can you elaborate on "does not work" -- it's unclear from your issue

The codes are not ignored. The setting has no effect, as if it were not present.

**Comment by WhyNotHugo** [comment]
> (note also that your syntax doesn't work for flake8 either

It does. I'm using that syntax on many projects using flake8 and the ignores are applied. [Here's](https://github.com/pimutils/todoman/) an example. Running flake8 on that project correctly ignores the specified codes.

**Comment by asottile** [comment]
just so you know:

pycodestyle interprets your setting as: `["W503",  "# Line jump before binary operator.\nE501", "# We rely on bugbear's B905 for this."]`

flake8 interprets your setting as `["W503", "#", "Line", "jump", "before", "binary", "operator.", "E501", "#", "We", "rely", "on", "bugbear's", "B905", "for", "this".]`

I'll leave the interpretation of "It does work" up to you

**Comment by WhyNotHugo** [comment]
Ah, that's much clearer, thanks.
