### ISSUE TITLE
A request to rename pycodestyle

### ISSUE THREAD

**Issue by DutKulang** [PyCQA/pycodestyle#1131]
it has been noticed that typing in the word `pycodestyle` into the terminal is a burden, the word too is not sexy but just lousy.
I suggest it be renamed to `Joy` a  3 digit word easy to remember and type.

After **Joy Buolamwini** 

Joy Buolamwini is a <ins> Black female computer scientist and researcher at MIT </ins>. Joy is also the founder of the Algorithmic Justice League, which focuses on making tech more equitable and accountable. She is on the Global Tech Panel, advising governments around the world on using AI technology appropriately.

She holds a master's degree and Ph.D. in media arts and sciences from MIT. Her groundbreaking graduate thesis discusses gender and racial basis in artificial intelligence technology at companies like Amazon, Microsoft, and IBM. She describes herself as a "poet of code" and writes about AI in the popular press.

She has received recognition for her role as one of the most influential women in computer science, including being named as one of Forbes' 30 Under 30, MIT Tech Review's 35 under 35, and Fortune's World's 50 Great Leaders. More than 1.4 million people viewed her TED talk on algorithmic bias. 

[Read more](https://www.computerscience.org/resources/most-influential-women-computer-science/)

**Comment by asottile** [comment]
joy is [taken on pypi](https://pypi.org/project/joy/)

we were already forced to rename the project once (from `pep8`), which still hasn't really [been properly realized](https://pepy.tech/project/pep8) (a million downloads a month of the project that doesn't exist any more!)

renaming is a big pain in the ass so it's not going to happen
