### ISSUE TITLE
Support .editorconfig

### ISSUE THREAD

**Issue by docwhat** [PyCQA/pycodestyle#1138]
Add support for [.editorconfig](https://editorconfig.org) configuration files for flags like:

- `--max-line-length=n`
- `--indent-size=n`

**Comment by sigmavirus24** [comment]
No. We aren't going to parse arbitrary things from a file we don't own. Our config logic is already disgusting spaghetti code from 10 years ago, and it works fine enough even though it's unmaintainable. We're not going to make it worse.

**Comment by docwhat** [comment]
Fair enough.  At least it is on record now for the next person who searches. :-)

**Comment by return42** [comment]
> No. We aren't going to parse arbitrary things from a file we don't own. 

🤔 https://editorconfig.org/ is now supported by every modern tool and has become a quasi-standard.

> Our config logic is already disgusting spaghetti code from 10 years ago, and it works fine enough even though it's unmaintainable. We're not going to make it worse.

The argument is more like a capitulation to one's own source code ... and such an argument comes from the "Python Code Quality Authority" of all places 🤦

**Comment by asottile** [comment]
"every modern tool" lmao
