### ISSUE TITLE
Multi-line noqa

### ISSUE THREAD

**Issue by odraencoded** [PyCQA/pycodestyle#1143]
Hello, sometimes I have code that shouldn't be formatted, so I use `fmt: off` or something similar with an autoformatter, but the linter still warns about the code. It seems I only have the option ti disable the linter for an entire file, disable one error, or disable one line. No way to turn if off for a part of a file.

Something like this would be nice:

    # noqa begin: E501
    ' code that shouldn't be linted '
    # noqa reset: E501

    # noqa begin: E501, E133
    ' code that shouldn't be linted '
    # noqa reset

**Comment by asottile** [comment]
there are several duplicates in the issue tracker already with the feature declined
