### ISSUE TITLE
test_check_nullbytes regressed on 3.11.4

### ISSUE THREAD

**Issue by mweinelt** [PyCQA/pycodestyle#1151]
We've updated python311 from 3.11.3 to 3.11.4 and now the following test has regressed. Works fine on 3.10.12 though.

```
pycodestyle-aarch64-linux> FAIL: test_check_nullbytes (test_api.APITestCase.test_check_nullbytes)
pycodestyle-aarch64-linux> ----------------------------------------------------------------------
pycodestyle-aarch64-linux> Traceback (most recent call last):
pycodestyle-aarch64-linux>   File "/build/pycodestyle-2.10.0/testsuite/test_api.py", line 333, in test_check_nullbytes
pycodestyle-aarch64-linux>     self.assertTrue(stdout.startswith(expected),
pycodestyle-aarch64-linux> AssertionError: False is not true : Output 'stdin:1:1: E901 SyntaxError: source code string cannot contain null bytes\n' does not start with 'stdin:1:1: E901 ValueError'
pycodestyle-aarch64-linux> 
```

**Comment by asottile** [comment]
next time please try the latest revision

**Comment by mweinelt** [comment]
Fails on 54b053e97180d10283354e7cdaaa5a2b1a0f434e all the same. You created a special case for 3.12, but this is 3.11.4.

https://github.com/PyCQA/pycodestyle/blob/54b053e97180d10283354e7cdaaa5a2b1a0f434e/testsuite/test_api.py#L331-L336

**Comment by s3v-** [comment]
> Fails on [54b053e](https://github.com/PyCQA/pycodestyle/commit/54b053e97180d10283354e7cdaaa5a2b1a0f434e) all the same. You created a special case for 3.12, but this is 3.11.4.
> 
> https://github.com/PyCQA/pycodestyle/blob/54b053e97180d10283354e7cdaaa5a2b1a0f434e/testsuite/test_api.py#L331-L336

Changes was backported to 3.11: https://github.com/python/cpython/pull/104195
Currently we have a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1042121) in Debian (Python 3.11 in stable, testing and sid ATM).

**Comment by asottile** [comment]
@s3v- you're trying to build 2.10 which is relatively old -- you'd probably have a better time with latest
