### ISSUE TITLE
2.11.0 sdist is missing some test files and doc sources

### ISSUE THREAD

**Issue by mgorny** [PyCQA/pycodestyle#1183]
The 2.11.0 release seems to be missing the `testing` directory that is required for the test suite. As a result, running the test suite from sdist now fails:

```pytb
________________________________________________ ERROR collecting tests/test_shell.py _________________________________________________
ImportError while importing test module '/tmp/pycodestyle-2.11.0/tests/test_shell.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_shell.py:8: in <module>
    from testing.support import ROOT
E   ModuleNotFoundError: No module named 'testing'
```

Furthermore, it seems that the documentation sources are no longer packaged whereas they were present in 2.10.0 and used by Gentoo to provide documentaiton for users.

**Comment by martinjungblut** [comment]
As an openSUSE contributor, I can confirm this is impacting us as well.

For now, we might circumvent this by downloading the git tag tarball from `https://github.com/PyCQA/pycodestyle/archive/refs/tags/2.11.0.tar.gz`. I just checked the Gentoo ebuild @mgorny.

It would be nice to have an upstream solution.

**Comment by asottile** [comment]
please read the PR and adjust your packaging
