### ISSUE TITLE
Readthedocs documentation is out of date

### ISSUE THREAD

**Issue by intgr** [PyCQA/pycodestyle#1184]
The `pycodestyle` documentation build has been failing for a few weeks.

See the latest build output here: https://readthedocs.org/projects/pycodestyle/builds/21445691/

Exception text from the error:

* "sphinx.errors.ConfigError: There is a programmable error in your configuration file:"
* "TypeError: Expected maxsize to be an integer or None"

**Comment by asottile** [comment]
@sigmavirus24 I don't have access to the admin thingy to adjust the settings unfortunately

**Comment by sigmavirus24** [comment]
Added you @asottile

**Comment by asottile** [comment]
@sigmavirus24 I still don't have access it seems -- but I threw a WAG of a config file up and it seems to have fixed it

via #1185
