### ISSUE TITLE
Run a Django project using Github Actions workflow but at some point install flake8 to ignore W191,E501 errors only.

### ISSUE THREAD

**Issue by kevindRuby** [PyCQA/pycodestyle#1188]
Lets say I want to run an Actions workflow to install flake8 where flake8 will ignore errors W191 and E501 e.g. --ignore=W191,E501,  how do I do this in the yml file?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
