### ISSUE TITLE
Testing using sdist?

### ISSUE THREAD

**Issue by CameronNemo** [PyCQA/pycodestyle#1196]
This is a followup to #1183, because conversation was locked there prematurely.

There was a comment made "please read the PR and adjust your packaging", but it is not clear what that comment means.

What PR (assuming PR stands for pull request and not press release) is being referred to? How do you suggest packagers update their packaging?

**Comment by asottile** [comment]
testing using the sdist is not supported -- I don't particularly care how you test that's on you and your particular setup.

if you can't find the pull request I would recommend learning to use `git log` or watching the repository so you can properly support your users
