### ISSUE TITLE
E123 handling not according PEP8 ?

### ISSUE THREAD

**Issue by rumpel360** [PyCQA/pycodestyle#1200]
Flake8 (VSC extension) throws indentation errors E123 for multiline expressions that should be fine with PEP8 rules in my opinion :

![Screenshot_E123](https://github.com/microsoft/vscode-flake8/assets/91403966/5dbd5819-cc31-4829-a914-fbb25ebc1ebf)

PEP8 site screenshot:
![Screenshot_PEP8_Indentation](https://github.com/microsoft/vscode-flake8/assets/91403966/1e551cc8-282d-4cf5-a556-0399830ad3fb)

PEP8 site link:
[https://peps.python.org/pep-0008/#indentation](url)

**Comment by asottile** [comment]
E123 is disabled by default and is something you have to opt into if you want that style.  you probably used ignore instead of extend-ignore

**Comment by rumpel360** [comment]
Thanks for info !
