### ISSUE TITLE
List unpack operator in assignment triggers false positive E999

### ISSUE THREAD

**Issue by jnluy** [PyCQA/pycodestyle#1208]
![274593138-9ec195f1-738f-4d0c-8274-2d519adfa182](https://github.com/PyCQA/pycodestyle/assets/50705586/a8650b84-933e-47e7-acf0-5f31174754cf)

**Comment by asottile** [comment]
[don't make screenshots of code](https://youtu.be/svlsnZFWWDE)

this syntax is only valid in 3.11+ so you need to be using an appropriate version of Python to lint it
