### ISSUE TITLE
Doc: StyleChecker(quiet) not documented

### ISSUE THREAD

**Issue by buhtz** [PyCQA/pycodestyle#1230]
In the docs about [Test automation](https://pycodestyle.pycqa.org/en/latest/advanced.html#automated-tests) you can find this line:

    style = pycodestyle.StyleGuide(quiet=True)

The argument `quiet` is not in the docs.
Are there any other arguments missing?

**Comment by sigmavirus24** [comment]
I'm fairly sure it's all auto-generated. Given the primary user is the CLI itself and the class allows for kwargs, there isn't much to document. I believe any CLI argument can be passed. But that's a moving target and I'm not certain it's worth the effort to document that in so many places.
