### ISSUE TITLE
suppress <name> may be undefined, or defined from star imports

### ISSUE THREAD

**Issue by qbnil** [PyCQA/pycodestyle#1233]
Is there a way to suppress this warning, i checked the docs but i didn't find anything in the imports section

**Comment by asottile** [comment]
pycodestyle does not have a diagnostic like that.  you must be confusing it for some other project

**Comment by qbnil** [comment]
![Uploading image.png…]()

**Comment by qbnil** [comment]
![image](https://github.com/PyCQA/pycodestyle/assets/130576530/7adfd587-1f6f-4cea-bbce-ef44fc1545bb)
Where do you thing it comes from then

**Comment by qbnil** [comment]
it's flake8, figured it, sorry
