### ISSUE TITLE
E711 not raised on '==' when comparing Enum

### ISSUE THREAD

**Issue by JamesPhillips-scoota** [PyCQA/pycodestyle#1262]
As Enums are singletons and should be compared using 'is', I expected E711 to be raised when comparing Enums using '=='. 

Something like:
```
from enum import Enum
class Color(Enum):
    RED = 1
    GREEN = 2
    BLUE = 3
```

then later 
`assert Color.RED == Color.RED`

I would expect the above to raise E711 but it does not.

**Comment by asottile** [comment]
pycodestyle just analyzes source, it cannot know the types
