### ISSUE TITLE
An empty file ends with a newline raise W391 blank line at end of file

### ISSUE THREAD

**Issue by EeyoreLee** [PyCQA/pycodestyle#1273]
The W391 rule specifies that Python files should end with a newline character. Does this not include empty files, such as `__init__.py`

**Comment by asottile** [comment]
an empty file should be 0 bytes

**Comment by EeyoreLee** [comment]
@asottile - I couldn't find any instructions regarding empty files in PEP8, and flake8rules said any file should not have zero, two or more than two newline in python file.

**Comment by asottile** [comment]
flake8rules is an unaffiliated third party and not to be trusted
