### ISSUE TITLE
False E251 and E202 for f-strings

### ISSUE THREAD

**Issue by MikhailRyazanov** [PyCQA/pycodestyle#1274]
(I did search for duplicates and found many of them, so this issue apparently affects many users, but so far has been rejected using invalid arguments.)

Current Python documentation for f-strings [says](https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals):
> To display both the expression text and its value after evaluation, (useful in debugging), an equal sign `'='` may be added after the expression.
> ...
> Spaces after the opening brace `'{'`, within the expression and after the `'='` are all retained in the output.
> ...
> Some examples of formatted string literals:
> ```python
> ...
> >>> f"{ foo = }" # preserves whitespace
> " foo = 'bar'"
> >>> line = "The mill's closed"
> >>> f"{line = }"
> 'line = "The mill\'s closed"'
> >>> f"{line = :20}"
> "line = The mill's closed   "
> >>> f"{line = !r:20}"
> 'line = "The mill\'s closed" '
> ```

PEP 701 “Syntactic formalization of f-strings” also [says](https://peps.python.org/pep-0701/#handling-of-f-string-debug-expressions):
> ...as specified currently, f-string debug expressions preserve whitespace in the expression, including spaces after the `{` and the `=` characters. This means that the raw string contents of the expression part of the f-string must be kept intact...

So these spaces within f-strings are totally _expected_, intentionally and explicitly allowed by the language documentation and are desirable in many cases; they are significant parts of the format specifier and not a question of the optional source-code style.

Moreover, the E251 error message “unexpected spaces around keyword / parameter equals” is clearly misleading/inapplicable here because the [`f_expression`](https://docs.python.org/3/reference/lexical_analysis.html#grammar-token-python-grammar-replacement_field) is neither a “keyword” nor a “parameter”.

Please don't ignore.

**Comment by sigmavirus24** [comment]
Duplicate of #1201

In the future, please search **closed and** open issues before creating new ones that are duplicates.
