### ISSUE TITLE
Add option to use tabs instead of spaces

### ISSUE THREAD

**Issue by glarrain** [PyCQA/pycodestyle#131]
While it is not endorsed by PEP8, it does acknowledge many users prefer tab indentation over spaces indentation. 

Using this tool, one can disable "W191 indentation contains tabs", but other errors will be raised inappropriately, such as:
- E122 continuation line missing indentation or outdented
- E127 continuation line over-indented for visual indent
- E128 continuation line under-indented for visual indent

The case of "E101 indentation contains mixed spaces and tabs" seems more complex because it is alright for continuations lines but not for regular statements.

What do you think?

**Comment by flying-sheep** [comment]
E101 (mixed tabs and spaces) still happens when there’s triple-quoted strings (beginning with spaces) and the code is indented with tabs
