### ISSUE TITLE
modify 712 error message

### ISSUE THREAD

**Issue by smichr** [PyCQA/pycodestyle#134]
If someone writes `if foo == True` this strictly has the equivalent meaning as `if (foo is True or foo == 1)` but the message printed from pep8 says "E712 comparison to True should be 'if cond is True:' or 'if cond:'".

The first option is more restrictive (as the foo = 1 will no longer pass).

The 2nd option is not the same e.g. `if foo` would pass for foo = range(3), foo = 1 or foo = True whereas the original would have only passed with True or 1.

I would suggest that the message be changed to

E712 comparison to True should be 'if cond is True or cond == 1' or 'if cond is True' (if the case of 1 is not an option).

**Comment by IanLee1521** [comment]
Closing due to this being explicitly a part of the PEP-8 document, see the end of the [programming issues](https://www.python.org/dev/peps/pep-0008/#programming-recommendations) section.

**Comment by hrichardlee** [comment]
Apologies for commenting on a long-dead issue, but one possibility which was never mentioned was changing the message to still include both options, but with a preference for the 95% case that @florentx mentions above:
> E712 comparison to True should be 'if cond' or in some cases 'if cond is True:'

I'm happy to make the pull request if it has a chance of being accepted.
