### ISSUE TITLE
E302 requires blank lines before first function in a file if it has a comment

### ISSUE THREAD

**Issue by yole** [PyCQA/pycodestyle#174]
```
# coding=utf-8
def foo():
    pass
```

This is highlighted as "expected 2 blank lines, found 0". If a function does not have a leading comment, pep8.py doesn't require me to put blank lines before it. This is inconsistent and is not required anywhere in the PEP 8 standard.

**Comment by dradetsky** [comment]
I may be misunderstanding something, but I understood this to be fixed a while ago. I'm using pep8 1.5.7. If I begin a file with

```python
# comment comment comment comment comment comment comment comment comment comment
class Foo(object):
    pass
```
It says there is no syntax error. But if I wrap it to:

```python
# comment comment comment comment comment comment comment comment
# comment comment
class Foo(object):
    pass
```
I get "E302 expected 2 blank lines, found 0" for the "class" line.

Was this fixed? Is there a config opt that turns it off? I couldn't find it in the docs.

**Comment by jayvdb** [comment]
Please see analysis on #412
