### ISSUE TITLE
Trailing whitespace in multiline strings

### ISSUE THREAD

**Issue by sn6uv** [PyCQA/pycodestyle#194]
I have a raw string with significant trailing whitespace: 

```
class Example:
    r"""
    >> " "    (* trailing space on following line *)
     = 
    >> ""     (* no trailing space on following line *)
     =
    """
```

`pep8` reports W291 for trailing whitespace within the string.

1) Is the trailing whitespace in my example even PEP8 non-compliant??
2) Is there a workaround without ignoring W291 completely?

Edit: Possible duplicate: https://bugs.launchpad.net/ubuntu/+source/pep8/+bug/702362

**Comment by sigmavirus24** [comment]
@gyermolenko yes, that is the current way to work around this when you need trailing white space inside a multi-line string.
