### ISSUE TITLE
Windows config path is invalid, can't config pep8

### ISSUE THREAD

**Issue by SanderP** [PyCQA/pycodestyle#199]
Hi,

I installed flake8 using activestate pypm. With some messing around I was able to integrate it into vim, it now runs flake8 on every python file save, cool. I want to configure pep8 to relax some of the checking. For instance the default vim indentation for line continuation doesn't jive with pep8. I like the vim python indentation fine and think pep8 is too strict in this case. Trouble is I can't figure out how to configure pep8 on windows. Part of the pep8 -h output says "--config=path      config file location (default: C:\Users\sanderp\.pep8)". Unfortunately this is an invalid path. You can't create a directory like that. I created a file _pep8 ala _vimrc but it appears to get ignored.

Is this a problem with the activestate port? Something you can help with? Maybe just a documentation update? 

Thanks,

    Sander

**Comment by IanLee1521** [comment]
Going to close as this hasn't been updated in a long time. If there are still issues with Windows configuration, please open a new issue. Thanks!
