### ISSUE TITLE
pep8.py does not conform to pep-257

### ISSUE THREAD

**Issue by dpursehouse** [PyCQA/pycodestyle#228]
Running pep257.py on pep8.py results in several warnings:

- First line should end with a period.
- Blank line missing after one-line summary.
- Multiline docstring should end with 1 blank line.
- First line should be in imperative mood ('Do', not 'Does').
- One-liner docstrings should fit on one line with quotes.
- Class docstring should have 1 blank line around them.

**Comment by IanLee1521** [comment]
Working on a patch for this now.

@Nurdok -- I'm curious if you might have any ideas why I get:

```
pep8.py:1798 in public method `__init__`:
        D102: Missing docstring in public method
```

When clearly [pep8.py:1798](https://github.com/PyCQA/pycodestyle/blob/master/pep8.py#L1798) `__init__` is not a public method? It looks like you don't have this issue [with pydocstyle itself](https://github.com/PyCQA/pydocstyle/blob/master/src/pydocstyle.py#L96).

Tested with pydocstyle version `1.0.0` and `1.0.0-rc1 @ b413c56`

**Comment by Nurdok** [comment]
`__init__` is considered a public method. The line in pydocstyle does not
generate an error because it's in a non public class (according to
`__all__`).

**Comment by IanLee1521** [comment]
Ah. Hmm, any recommendations on docstrings other than `"""Create FooBar object."""` or similar?

**Comment by Nurdok** [comment]
This is usually the place to document init parameters.
