### ISSUE TITLE
Command line option to generate a config file section

### ISSUE THREAD

**Issue by Bengt** [PyCQA/pycodestyle#235]
pep8 has the ability to use a rcfile (see #22) and there is an example in the docs for such a file (see #139 and [rtd.org/intro#config](http://pep8.readthedocs.org/en/latest/intro.html#configuration)). pep8 lacks but a command line option to generate the `[pep8]` section of such a file. [PyLint for example](http://linux.die.net/man/1/pylint) has such a sub-command:

> --generate-rcfile
>     Generate a sample configuration file according to the current configuration. You can put other options before this one to get them in the generated configuration.

**Comment by IanLee1521** [comment]
Going to go ahead and close this since it hasn't gained any extra support. If we think it is worth while at some point we can reopen or create a new issue. Thanks for the suggestion though!
