### ISSUE TITLE
config not being loaded from ~/.config/pep8

### ISSUE THREAD

**Issue by mcandre** [PyCQA/pycodestyle#245]
I followed the [official documentation](http://pep8.readthedocs.org/en/latest/intro.html#configuration) for configuration, placing my settings in `~/.config/pep8`, in INI format.

When I put a `tox.ini` at my project root directory, pep8 successfully loads my custom configuration. But when I move the same settings to `~/.config/pep8`, pep8 ignores them.

**Comment by IanLee1521** [comment]
Closing as there has been no update to this issue in almost 2 years.
