### ISSUE TITLE
Optionally ignore project config files

### ISSUE THREAD

**Issue by blueyed** [PyCQA/pycodestyle#253]
While you can use `/dev/null` for `--config`, there is no option to skip reading/using any project config files.

This would be useful to configure pep8 via a single config file / command line options.

A workaround appears to be to create an empty config file (`touch setup.cfg`) in the current directory.

**Comment by IanLee1521** [comment]
Since there is a possible work around listed in the original report, I'm going to go ahead and close this. If there is a proposed way to handle this, please reopen and provide a pull request. Thanks!
