### ISSUE TITLE
Handling of single line function definitions

### ISSUE THREAD

**Issue by ncoghlan** [PyCQA/pycodestyle#277]
To avoid the practice of assigning lambda expressions to names, PEP 8 now includes the guideline "Always use a def statement instead of an assignment statement that binds a lambda expression directly to a name."

Currently, the PEP 8 approved style for single line functions definitions generates an error, but the disallowed style is accepted:

```
$ cat > foo.py
def f(): pass
f = lambda: None
$ pep8 foo.py
foo.py:1:8: E701 multiple statements on one line (colon)
```

It would be better if there was an exception to E701 for "def" statements, and a new rule to complain about having a lambda definition as the sole expression on the right hand side of an assignment statement.

**Comment by merwok** [comment]
FWIW lambdas with names are useful in tests, for instance when replacing methods with stubs (using pytest.monkeypatch and pretend.stub in my case).
