### ISSUE TITLE
E126 issue

### ISSUE THREAD

**Issue by remram44** [PyCQA/pycodestyle#290]
It is weird that this code should pass without error:

``` python
fp.write("%s"
         " is one" % (
             1,))
```

but this one spits out E126 ("continuation line over-indented for hanging indent") on line 2:

``` python
fp.write("%s" % (
             1,))
```

Is this intended? (no pun indented)

**Comment by remram44** [comment]
I'm not saying the program behaves differently from the algorithm, I'm arguing that the algorithm is wrong.

**Comment by IanLee1521** [comment]
Hi @remram44 --

I'm not sure I follow you about the algorithm being wrong.  In your first example:

```python
fp.write("%s"
         " is one" % (
             1,))
```

the second line is visually indented, and the the third is hanging indented from the second (by four spaces).

In the second:

```python
fp.write("%s" % (
             1,))
```

the second line is indented by 13 spaces, and is also not visually indented.

As far as I can tell, the E126 error you are getting is intended (going back to your original question).

**Comment by remram44** [comment]
I understand where the algorithm comes from and why it's been written this way. However, looking at the snippet as a whole and not line-by-line as an algorithm would, I find it weird for the second to be wrong if the first is correct, since it is *semantically, to a human*, exactly the same sequence of tokens: a string then parameters between parens.

I understand why it would be easier to state (in PEP8) or to formalize (for `pep8.py`), but the result is just broken: whether or not the string is split in multiple lines can't affect the indentation level of the format parameters.

You might not be able to fix this for PEP8 or find the rules too hard to formalize but, looking at this from a high-level, surely you can see that these are no reasonable indentation checks.

**Comment by IanLee1521** [comment]
So I guess I'm curious what your solution would be?  Should both your examples be allowed? Both an error?

Personally I believe that example 1 is ok (though not preferred) and example 2 should be an error (it looks ugly to me)

My preference would be to use either:

```python
fp.write("%s is one" % (
    1,))
```

or even better (to me):

```python
msg = "%s is one" % (1,)
fp.write(msg)
```
