### ISSUE TITLE
warnings for trailing comma ?

### ISSUE THREAD

**Issue by jvanasco** [PyCQA/pycodestyle#308]
I'm not sure if this is appropriate for pep8 or not, as I couldn't find a reference in PEP8 and this deals with a feature of python / idiomatic way of writing code -- a trailing comma will cast something as a tuple.

But it is also a 'gotcha' that pops up every now and then, and I thought a warning might be a useful idea as an option.

This is usually great -- but if you're editing/reformatting a lot of code (particularly dicts) and leave a trailing comma, in there... all of the sudden your objects change and your code breaks.  everything is valid python code, so it runs perfectly and passes pep8.

this often happens to me when reformatting dicts:

```
original =  { 
    "a": {},
    "b": {}
},
```

it would be really great if there were an option to enable warnings for code like this.  

flake8 runs early in our build/test/deploy pipeline, so issues don't get discovered until later on in our tests.  if we could catch it earlier, that would be great.

**Comment by chris-rands** [comment]
Reading [PEP8](https://www.python.org/dev/peps/pep-0008/#when-to-use-trailing-commas), there is some indication that trailing commas should not be used in at least some contexts: 

> 
>  When to use trailing commas
> 
> Trailing commas are usually optional, except they are mandatory when making a tuple of one element (and in Python 2 they have semantics for the print statement). For clarity, it is recommended to surround the latter in (technically redundant) parentheses.
> 
>     Yes:
> 
>     FILES = ('setup.cfg',)
> 
>     OK, but confusing:
> 
>     FILES = 'setup.cfg',
>
