### ISSUE TITLE
trailing comma for 'ignore' in config effectively ignores all

### ISSUE THREAD

**Issue by jvanasco** [PyCQA/pycodestyle#320]
originally filed to flake8, refiled here [https://bitbucket.org/tarek/flake8/issue/162/trailing-comma-for-ignore-in-config]

by accident I had a trailing comma in my config:

    ignore = E121,E122,E123,E126,E127,E251,E501,E701,F401,F403,F812,F841,

this had the effect of ignoring all tests. no warning was given.

removing the trailing comma shows all the various issues:

    ignore = E121,E122,E123,E126,E127,E251,E501,E701,F401,F403,F812,F841

so a malformed config file will raise no issues, and not run any tests (or not output the results of them)

I think it would be best to either:

1- issue a fatal warning if a trailing comma is detected in the config 
2- simply not have this behavior, if possible

**Comment by IanLee1521** [comment]
This was resolved by commit e7d64d30 which improved parsing of multi-options.
