### ISSUE TITLE
"W602 deprecated form of raising exception" with "raise t, v, tb"

### ISSUE THREAD

**Issue by gholt** [PyCQA/pycodestyle#34]
I'm not entirely sure this is a bug in pep8, but I can't an alternative way to format the following code:

```
try:
    foo()
except:
    t, v, tb = sys.exc_info()
    try:
        bar()
    except:
        pass
    raise t, v, tb
```

In this particular case, bar() could raise an exception I don't care about, so the last raise can't be just "raise" because it might just reraise bar()'s exception and I want the original exception. I did a bunch of searching, but I can't find where "raise t, v, tb" is deprecated, just things like "raise v".

Confirmation on a bug or information on setting me straight would be much appreciated. :)

**Comment by mforbes** [comment]
@florentx You might like to check the order of your arguments in your suggestion: I think it best be ``(exc_type, exc, tb) = sys.exc_info()``.
