### ISSUE TITLE
Enforce 72 character docstring line width

### ISSUE THREAD

**Issue by mblayman** [PyCQA/pycodestyle#344]
PEP8 states:

> For flowing long blocks of text with fewer structural restrictions (docstrings or comments), the line length should be limited to 72 characters.

The current implementation only enforces the maximum line length (`E501`). I'd like to suggest the addition of an `E503` error to enforce the restriction of these "flowing long blocks of text."

**Comment by timj** [comment]
I would really welcome this test as we have continuing arguments on our project about docstring lengths (I'd like comment blocks to be restricted to that same length as well) vs other line lengths and distinguishing the two (as is done in PEP8) would be incredibly helpful. I understand backwards compatibility issues but can I suggest that we deal with this by having a new config parameter for `max-docstring-length` and default it to whatever `max-line-length` is set to. Then existing users would not even notice a change but people would be able to explicitly set `max-docstring-length` to 72 or 79 or whatever and see the E503 errors.

**Comment by timj** [comment]
@sigmavirus24 would you consider accepting a patch as I describe above? This should be a backwards compatible approach.

**Comment by sigmavirus24** [comment]
@timj would it not be better to add this to pydocstyle?

**Comment by timj** [comment]
Hmm. This is something covered by PEP8 so it would seem to be relevant to this. Does pydocstyle get called by flake8? @jonathansick do you have an opinion?

**Comment by sigmavirus24** [comment]
@timj `flake8-docstrings` is what calls pydocstyle from Flake8. Either way, I'd rather not implement this here if it would be more appropriate in pydocstyle or vice-versa.

**Comment by timj** [comment]
pycodestyle explicitly states: "pycodestyle (formerly pep8) is a tool to check your Python code against some of the style conventions in PEP 8."

[PEP 8](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) says:

> For flowing long blocks of text with fewer structural restrictions (docstrings or comments), the line length should be limited to 72 characters.

so it doesn't seem unreasonable for the program that checks PEP8 compliance to have checks listed in PEP8.

PEP257 (covered by pydocstyle) doesn't mention line lengths and doesn't mention comment strings. This strongly suggests to me that pycodestyle should be dealing with warnings about docstring and comment line length.

**Comment by sigmavirus24** [comment]
@timj exactly, against **some** of the style conventions. Just because a convention exists in the document does not mean it needs to be implemented here. For example, the naming conventions live in a Flake8 plugin called `pep8-naming` and only strives (but barely accomplishes) implementing checks for that. `pydocstyle` likewise does not only implement PEP 257 checks as it allows for other conventions and is very configurable. It also has the benefit of directly inspecting docstrings via the AST and that should allow it to discern this more readily that pycodestyle would. In other words, to implement it there *should* be far less work. So while it's not the right place by vague document relations it probably is the best place for accuracy, relevance to users, and ease of implementation.

**Comment by timj** [comment]
Does `pydocstyle` recognize comments as well as docstrings?

**Comment by brianv0** [comment]
I've got a PR in for this if anyone is interested. I hoped to meet everyone's needs in it, but it might require a bit of discussion. 

In short, I don't believe this will impact anyone. I've set the default `max-doc-length` to 79, but that's mostly so that the code in pycodestyle.py and other tests pass without too much rewriting of both pycodestyle and unit tests (much of the doc length in pycodestyle is over 72 characters).

**Comment by timj** [comment]
Oh, so you are setting the default to 79 because you are disabling the warning by default. The other options is to default to max-line-length and disable W504 only if you are using that default (since you'll get a standard long line warning as you would before).

**Comment by brianv0** [comment]
The behavior was updated in the PR. The check is not active (and not on the default ignore list). Instead, the check is only activated when a `--max-doc-length=n` is entered (or corresponding `max_doc_length` in config file)

**Comment by timj** [comment]
I like the approach of the check only activating if you specify a doc length.

**Comment by timj** [comment]
@sigmavirus24 what do you think of #674?

**Comment by McSinyx** [comment]
Is there a way to only checks for docstring line width (and ignore comments)?  I know that's not what PEP 8 advises but I'd love to have it.

**Comment by asottile** [comment]
@McSinyx seems there isn't currently, both comments and triple-quoted-strings both trigger W505 (if they were separate codes you could ignore one of them)

**Comment by asottile** [comment]
The original issue as written is solved by #674 though (and therefore this can be closed)

**Comment by McSinyx** [comment]
Should I file an issue (or even a PR) on that so this issue can be closed in peace then?

My proposal is to have 3 cases handled:
* Multi-line docstring: `max_doc_length`, default to `max_line_length` (current behavior)
* Single-line docstring: `max_single_doc_length`, default to `max_doc_length + 3`
* Comment block: `max_comment_length`, default to `max_doc_length`

**Comment by asottile** [comment]
I'm not a maintainer here, but I don't think the complexity of a bunch of new settings is a good idea -- also your current proposal allows single line docstrings to extend beyond max_line_length

**Comment by timj** [comment]
I agree this should be closed and a new ticket used to discuss more fine-grained control.  I'm really happy with the current situation and have no problem forcing my comment lines to match the docstring constraint.

**Comment by brianv0** [comment]
I would say that it's probably not quite trivial because docstrings are block comments/strings in specific positions in the code (right after function/class definition), so there's positional awareness involved. For normal comments, I think you could do that. Regardless - it needs a new issue.
