### ISSUE TITLE
Support specifying an output file

### ISSUE THREAD

**Issue by sigmavirus24** [PyCQA/pycodestyle#362]
I realize this was previously discussed in #66 but this has come up several times now for flake8. The most recent discussion can be found [here](https://gitlab.com/pycqa/flake8/issues/15).

Here's the reasoning:

An increasing people are using pep8 and flake8 as part of their test environments and an increasingly popular way of doing this is with `tox`. Unfortunately, `tox` does not support redirection of standard out the way a shell normally does nor should it have to.

It would be rather trivial to add support for this feature and I'm happy to send a pull request to add it. It's also useful so that the results of the test run can be uploaded somewhere, even when run from within tox.

Are we willing to reconsider our position on this?

**Comment by jogo** [comment]
This feature sounds useful for the OpenStack CI use case. Currently we run https://github.com/openstack-infra/project-config/blob/master/jenkins/scripts/run-pep8.sh and collect the console log via jenkins. But the output can be hard to read with all the other output in the console

http://logs.openstack.org/69/136869/19/check/gate-nova-pep8/fbf8fd7/console.html#_2015-01-06_17_52_11_814

**Comment by sigmavirus24** [comment]
Flake8 has implemented this for quite a while. Flake8 3.0 has a much more reasonable implementation.
