### ISSUE TITLE
Detecting unassigned triple quoted strings

### ISSUE THREAD

**Issue by unode** [PyCQA/pycodestyle#37]
Python doesn't provide a way to do block quotes other than prefixing all lines in a block with # .
Some people find this "too complicated" and have started to use triple quotes (""" or ''') to achieve a block quote like behavior.

Although not  explicitly stated in PEP8, this is considered by many bad practice and in some occasions confusion about how docstrings work.

In light of this, I propose that triple quotes that are not docstrings, are not assigned to variables, nor  contained in (), [] or {}, are treated as errors or raise a warning.

**Comment by slw07g** [comment]
"You can use multi-line strings as multi-line comments. Unless used as docstrings, they generate no code." - Guido Van Rossum, the python creator himself

https://twitter.com/gvanrossum/status/112670605505077248?lang=en
