### ISSUE TITLE
Tilde is treated as binary operator

### ISSUE THREAD

**Issue by czyzykowski** [PyCQA/pycodestyle#384]
Following code cause W503 to be reported, because ~ is treated as a binary operator, where in reality it is unary.
```
var = (1 &
       ~2)
```

**Comment by rkern** [comment]
Similarly, unary `-` is falsely being reported as a W503 violation.

```
[~/scratch]$ cat false_pep8.py
y = 75.0
z = 100.0
x = (y /
     -z)
[~/scratch]$ pep8 false_pep8.py
false_pep8.py:4:6: W503 line break before binary operator
[~/scratch]$ pep8 --version
1.7.0
```

**Comment by rkern** [comment]
I haven't tried #383 on the unary `-` case yet, but it looks like it would not fix this instance of the problem.

**Comment by Incognito** [comment]
+1 I also have this issue.
