### ISSUE TITLE
blank line at end of file

### ISSUE THREAD

**Issue by DXist** [PyCQA/pycodestyle#40]
What is more 'pythonic'  - to leave blank line at end of file or not? Most tools require blank line at end of file. There is no ugly message "\ No newline at end of file" in diff output.  Why does pep8 tool require no blank lines at end of file?

**Comment by jorgesumle** [comment]
W391 is annoying.

**Comment by The-Compiler** [comment]
@jorgesumle So turn it off? I find it useful.

**Comment by techtonik** [comment]
I remember there was some unix story about those linefeeds at the end of file, so this must be some unix kludge from the past and now is a cargo ritual. =)

**Comment by DXist** [comment]
Nice point from http://stackoverflow.com/questions/5813311/no-newline-at-end-of-file

```
The message is displayed because otherwise there is no way to tell the difference between a file where there is a newline at the end and one where is not. Diff has to output a newline anyway, or the result would be harder to read or process automatically.

Note that it is a good style to always put the newline as a last character if it is allowed by the file format. Furthermore, for example, for C and C++ header files it is required by the language standard.

```

So last new line is important for diff tools (including Github) and must have for C/C++. I guess early C development toolchain incorrectly handled last line without line terminator symbols.

I think new line is a part of best practices and I dislike editors/IDEs that don't put last new line by default. Rituals support common and clear coding style.
