### ISSUE TITLE
triple-quoted strings should always use double quote characters

### ISSUE THREAD

**Issue by jayvdb** [PyCQA/pycodestyle#423]
From https://www.python.org/dev/peps/pep-0008/#string-quotes

"For triple-quoted strings, always use double quote characters to be consistent with the docstring convention in PEP 257 ."

**Comment by sigmavirus24** [comment]
This would seem reasonable but would need to be introduced in 1.7.0 (assuming 1.7.0 is planned).

**Comment by IanLee1521** [comment]
Agreed, I think this would be a fine check to add in 1.7.0

**Comment by SylvainDe** [comment]
As a side-note, this is not added in 1.7.0 as the pull request is still waiting for additional information.

**Comment by SylvainDe** [comment]
So, as per the comments on https://github.com/PyCQA/pycodestyle/pull/428 , should we just close the issue and abandon the pull-request ?

**Comment by asottile** [comment]
agreed, given the resolution in #428
