### ISSUE TITLE
pep8 has conflicting definitions of a docstring

### ISSUE THREAD

**Issue by jayvdb** [PyCQA/pycodestyle#448]
pep8 has
- `DOCSTRING_REGEX` (used by `blank_lines`) which only allows `u` & `r` prefixes.  pep257 doesnt appear to exclude `b`, but it also doesnt explicitly mention it as allowed.
- `is_string_literal` (used by `module_imports_on_top_of_file`) which strictly matches the Python 2 string prefix pattern that includes `u`, `r` & `b`

`DOCSTRING_REGEX` dates back to 58a7812c, and the same rough restriction goes back to d8ee2baf in 2009.

`is_string_literal` is from 2014 (1ee296bc).  I dont see any discussion on https://github.com/PyCQA/pep8/pull/304 regarding why `r` should now be appropriate for a docstring, and should be different from `blank_lines`.

Consider

``` python
b"""foo"""

# `blank_lines` uses DOCSTRING_REGEX, which only allows `u` & `r` prefixes

import sys


class Foo(object):

    b"""Foo."""
    def blah(self):
        pass

    r"""Foo."""
    def baz(self):
        pass

    a = 1
    r"""Foo."""
    def hmmm(self):
        pass
```

Only one pep8 result:

```
test.py:11:5: E301 expected 1 blank line, found 0
    def blah(self):
    ^
```

Firstly, I have not found the part of pep8 which allows a docstring on the line preceding a function.

Quite the opposite actually.  Regarding docstrings, pep8 does say "This comment should appear after the def line."

If there is reason for docstrings on the preceding line, I then cant see why `b` should be excluded according to pep8, or pep257 if read as literally as seems very common around here, but of course it is very silly and should be excluded for common sense reasons, in both `blank_lines` and `module_imports_on_top_of_file`, and anywhere else relating to docstrings.

And finally regarding this segment of the `blank_lines` code, allowing `a = 1` above is clearly a bug.

**Comment by jayvdb** [comment]
Tangentially related.

Also notice that the code does not currently publicly advise that `r'..'` is not desirable.  It merely disregards `r'..'` silently.

If pep8 continues to make judgements about the appropriate string prefixes, I believe it should advise that `r'..'` is not desirable.

It could also advise that on Python 3 `ur'..'` is invalid syntax (http://bugs.python.org/issue15096), especially on Python 3, but currently that is being done by `pyflakes`, and I guess it might be a small complication for `flake8` to have both `pyflakes` and `pep8` emitting an error for the same problem.

**Comment by sigmavirus24** [comment]
Why is `r"""..."""` not desirable? 

Further, we don't advise on Syntax issues. We advise on *style*.

**Comment by jayvdb** [comment]
DOCSTRING_REGEX is not including `r`. I'm not sure whether that is a bug or a decision.

**Comment by sigmavirus24** [comment]
Likely a bug. Don't attribute to opinions (or malice) what can be attributed to mistake. `r""" ... """` is definitely desirable in some cases.

**Comment by asottile** [comment]
this seems correct -- bytestrings are not docstrings:

```pycon
$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def t():
...     b"""fooo"""
... 
>>> t.__doc__
>>> def f():
...     r"""foo"""
... 
>>> f.__doc__
'foo'
>>> def g():
...     u"""foo"""
... 
>>> g.__doc__
'foo'
```
