### ISSUE TITLE
Pep8 test results are not getting parsed correctly by Bamboo

### ISSUE THREAD

**Issue by cesararevalo** [PyCQA/pycodestyle#467]
Hi, we are having issues (see https://jira.atlassian.com/browse/BAM-17049) getting Bamboo to parse the junit XML results properly. According to the Bamboo folks it would all be fixed if pep8 defined a non-empty classname string on the testcase sections.

-Cesar

**Comment by IanLee1521** [comment]
Hi @cesararevalo -- Would you be willing to provide a patch for this that I could review?

**Comment by IanLee1521** [comment]
@cesararevalo -- What is the commandline you're using that is causing this? Also what versions of Python and pycodestyle are you using?

**Comment by cesararevalo** [comment]
Hi Ian - this is the command we are using to run the pep8 tests:

py.test --pep8 --cache-clear -m pep8 -s --junitxml=tests/pep8.xml

**Comment by IanLee1521** [comment]
On my phone so I can't test, but that command line makes me think this is a bug with pytest rather than pycodestyle.

That is the command you are using to actually test and generate your xml from the looks of it.

**Comment by jayvdb** [comment]
Pinging @hpk42 who is a prominent dev on pytest-pep8 , and @The-Compiler who I see is also recently active there.

**Comment by The-Compiler** [comment]
Yeah, this looks like an issue with pytest-pep8 or pytest core - I suggest reporting it [in the pytest-pep8 tracker](https://bitbucket.org/pytest-dev/pytest-pep8/issues?status=new&status=open) for now, as I can't really help with JUnitXML stuff, never used it myself :wink:

**Comment by sigmavirus24** [comment]
I would vote to close this then since it's not actually a problem in pep8.

**Comment by IanLee1521** [comment]
Closing since this is not a pycodestyle bug. But I don't think it's pytest-pep8 either. Actually I think its core https://github.com/pytest-dev/pytest, specifically something in: https://github.com/pytest-dev/pytest/blob/master/_pytest/junitxml.py
