### ISSUE TITLE
Project rename -> "pycodestyle"

### ISSUE THREAD

**Issue by IanLee1521** [PyCQA/pycodestyle#481]
Per the discussion in #466, I'll be renaming this repo to "pycodestyle" in the next day or two, I'll close this issue and post to the code-quality mailing list once I do. Consider this my announcement of the pending name change! :)

**Comment by sigmavirus24** [comment]
@IanLee1521 please let me know in advance so I can be around on IRC in case anything goes sideways. (I don't anticipate that, but I'd like to plan for it regardless.)

**Comment by IanLee1521** [comment]
Thanks for the heads up. Guess it's good I got swamped. Why don't I just plan for Monday morning (ish)?

Also, what's a good IRC client for OSX?

**Comment by The-Compiler** [comment]
> Also, what's a good IRC client for OSX?

I've seen people use [Textual](https://www.codeux.com/textual/) much. If you prefer something console-based, probably [weechat](https://weechat.org/).

**Comment by sigmavirus24** [comment]
@IanLee1521 Monday morning-ish sounds good to me. :) https://webchat.freenode.net/ works too as a temporary client while you figure out your tastes. The channel is `##python-code-quality`` and I'm just realizing that should be in the meta documentation ;)

**Comment by IanLee1521** [comment]
Making the change now.

**Comment by sigmavirus24** [comment]
The project has been renamed so I've closed this. The other (related) issue is marked for 2.0 milestone so I'm leaving that open.
