### ISSUE TITLE
Unary `-` reporting as W503

### ISSUE THREAD

**Issue by IanLee1521** [PyCQA/pycodestyle#484]
Copying from https://github.com/PyCQA/pycodestyle/issues/384#issuecomment-176760177 per @rkern.

> Similarly, unary `-` is falsely being reported as a W503 violation.
> 
> ```
> [~/scratch]$ cat false_pep8.py
> y = 75.0
> z = 100.0
> x = (y /
>      -z)
> [~/scratch]$ pep8 false_pep8.py
> false_pep8.py:4:6: W503 line break before binary operator
> [~/scratch]$ pep8 --version
> 1.7.0
> ```

**Comment by sigmavirus24** [comment]
@rkern would you have time to try out #485?
