### ISSUE TITLE
pep8 is not called from ~/.locale/bin/

### ISSUE THREAD

**Issue by AntonKarmanov** [PyCQA/pycodestyle#492]
After install with pip3 there is ~/.locale/bin/pep8, but ~/.locale/bin/ is not in PATH by default (in Ubuntu, at least). So, it's impossible to start pep8 from terminal.
Ubuntu MATE 15.10, pep8 1.7.0

**Comment by sigmavirus24** [comment]
This is not an issue with this project. This is an issue with your system configuration. Questions are happily answered on [StackOverflow](https://stackoverflow.com/).

**Comment by AntonKarmanov** [comment]
I think, project must consider defaults of one of the most popular distro.

**Comment by The-Compiler** [comment]
This has nothing to do with pep8. `~/.local/bin` is just where `pip install --user` installs binaries to.

**Comment by AntonKarmanov** [comment]
Oh, got it, sorry for trouble you!

**Comment by sigmavirus24** [comment]
The forcibly patched defaults of your "most popular distro" also force the `--user` flag which is why you're having this trouble.
