### ISSUE TITLE
Config file search suboptimal

### ISSUE THREAD

**Issue by choppsv1** [PyCQA/pycodestyle#494]
I see that this seems to have gone a few iterations (the search path for config), but I think the current scheme is wrong. :)

I have a $HOME/.config/flake8 (flake8 uses pep8 so same applies to both I think). This is my default config for pep8/flake8, obviously these settings are set general enough to apply in any situation. I then have project specific files these are by definition more tailored to the project itself. In other words, formatting exceptions (line length space allowances, etc) in the ignore line in the project config are tailored to the project itself. In my case these are often different in different ways for each project than my generic default ones in $HOME/.config.

The currently scheme has my generic $HOME.config settings overriding the project specific ones. So basically I have to disable having generic settings as they will often be wrong for each project.

I suggest that by default the order should be reversed, i.e., load the $HOME based config, then look for project specific config letting it override the generic settings. Possibly a flag could be added to obtain the old behavior (or new, but I think my method makes more sense as a default).

Another option to consider would be to allow for ORing option values together which would then take the project settings and the users default settings into account. Perhaps a different option value name could be used to select the logical OR functionality.

**Comment by sigmavirus24** [comment]
> but I think the current scheme is wrong. :)

Except a lot of people rely on the current semantics. If you'd like to argue for different semantics, the proper place (since you're using flake8) is over on the flake8 project for version 3.0 which is removing this responsibility from pep8.

> The currently scheme has my generic $HOME.config settings overriding the project specific ones. So basically I have to disable having generic settings as they will often be wrong for each project.

What version of pep8 are you using? This sounds like a 1.6 series bug that was fixed in 1.7.

> flag could be added to obtain the old behavior

Please no more options (flags).

> Another option to consider would be to allow for ORing option values together which would then take the project settings and the users default settings into account. Perhaps a different option value name could be used to select the logical OR functionality.

Do you mean "If something is already set in one place, do not allow the file that takes precedence to override it?" I don't think we want that kind of behaviour.

**Comment by choppsv1** [comment]
Ian Cordasco <notifications@github.com> writes:

>> but I think the current scheme is wrong. :)
>
> Except a lot of people rely on the current semantics. If you'd like to argue for different semantics, the proper place (since you're using flake8) is over on the flake8 project for version 3.0 which is removing this responsibility from pep8.
>

I chose here b/c this is where the released tool is getting it's code
from as far as I could tell. I'll close this report.

For the Issue history it seems like the current code is not doing the
expected thing based on what you mentioned. My home config is being
viewed as cli configuration and overriding. Perhaps this is a flake8
bug after all.

    $ flake8 --version
    2.5.4 (pep8: 1.7.0, mccabe: 0.4.0, pyflakes: 1.0.0) CPython 3.5.1 on Linux
    $ flake8 -v jdsuocm/device.py
    local configuration: in /home/chopps/w/jdsu-ocm
    cli configuration: /home/chopps/.config/flake8
    checking jdsuocm/device.py

**Comment by choppsv1** [comment]
here's the shell snippet that gotted trimmed by github I guess...

$ flake8 --version
2.5.4 (pep8: 1.7.0, mccabe: 0.4.0, pyflakes: 1.0.0) CPython 3.5.1 on Linux
$ flake8 -v jdsuocm/device.py 
local configuration: in /home/chopps/w/jdsu-ocm
cli configuration: /home/chopps/.config/flake8
checking jdsuocm/device.py
...

**Comment by sigmavirus24** [comment]
Ah, this is a flake8 bug actually. That is fixed in the master branch of flake8.
