### ISSUE TITLE
False positive E251 on argument annotations with default parameters

### ISSUE THREAD

**Issue by agronholm** [PyCQA/pycodestyle#496]
PEP 8 specifies that when there's an argument annotation with a default value, the `=` should have spaces around it. Currently the pep8 tool complains about it:

    asphalt/core/concurrency/threads.py:69:46: E251 unexpected spaces around keyword / parameter equals

And the line of code in question:

    def threadpool(arg: Union[Executor, Callable] = None):

**Comment by IanLee1521** [comment]
Yeah, the tool pre-dates that functionality in CPython. I'd be happy to review a pull request to correct that issue.

**Comment by agronholm** [comment]
I beg to differ. Looking at the the code, it already seems to support this case, but the comma in the argument type expression is throwing it off.

**Comment by IanLee1521** [comment]
Ah, good catch, thanks! Was on my phone and didn't have the source code when I responded last night.
