### ISSUE TITLE
Update handling of breaking around binary operators: W503 vs W504

### ISSUE THREAD

**Issue by IanLee1521** [PyCQA/pycodestyle#498]
Based on the discussion that started on python-dev [1] and ended with an update to PEP-8 [2][3], the logic for allowing (preferring really) breaks to occur before rather than after binary operators.

[1] https://mail.python.org/pipermail/python-ideas/2016-April/039774.html
[2] http://bugs.python.org/issue26763
[3] https://hg.python.org/peps/rev/3857909d7956

**Comment by hai-ld** [comment]
How should we implement this patch, interface-wise? There are two options off the top of my head:
- provide an option to choose the preferred breaking style, with the new style as default
- or warning when inspected files containing both styles

**Comment by methane** [comment]
My opinion is just stop warning and more permissive about continuation line.
Current pydocstyle is stricter than Guido.  There are many cases "this is more readable, but pep8.py doesn't accept it."

See discussion in http://bugs.python.org/issue26763

**Comment by warsaw** [comment]
I also lean toward not warning about it.  It seems like it might be good to warn about mixed styles, but I think ultimately that will be more annoying than helpful.

**Comment by sigmavirus24** [comment]
#499 is the most straight forward way of solving this. This also allows others who *like* this rule to re-enable it by selecting it.

**Comment by hai-ld** [comment]
@sigmavirus24 If I understand it correctly, that means there is no way to:
- ensure consistent breaking
- enforce breaking before binary operator

Is it PyCQA's opinion that above points should be pylint's responsibilities?

**Comment by sigmavirus24** [comment]
@hai-ld please don't put words in my mouth. The immediate need is to turn this off. In my opinion a new check should be added which is also in the default ignore, otherwise we will cause a lot of problems. This means people will need to enable it by hand. (That said, if we wanted to add the new check in pycodestyle 2.0 we could break it very easily.)

**Comment by hai-ld** [comment]
@sigmavirus24 I'm sorry if there's any negative connotation in my comments, be assured that it's not intentional (I'm just not a native English speaker). Since you said "#499 is the most straight forward way of **solving** this", I thought that was the final solution and asked for confirmation.

**Comment by sigmavirus24** [comment]
The two comments after yours advocated for *not* warning about this particular style notion from PEP-0008. In that case, the most straight-forward way to solving the problem of warning about this is to disable it. It's not the end of all discussion though.

**Comment by IanLee1521** [comment]
Re-opening to allow discovery of this issue instead of new issues being opened.

**Comment by PositiveAlex** [comment]
Hi, could anyone write an updated status on this? I don't understand what I'm doing wrong.

**Comment by sigmavirus24** [comment]
@PositiveAlex you'll need to provide a lot more information than that if you'd like us to be able to help you.

**Comment by cas--** [comment]
@ailjushkin  Perhaps this quote from [referenced issue ](https://github.com/beetbox/beets/pull/2687)will help:

> I know about that flake8 warning, I did see it when running tox. Though I decided to ignore it as it is a bug. [1] [2] [3] [4]
>
> PEP8 was updated to allow both styles and even states breaking before (like I did) as the preferred style for new code. [5]
>
> For those reasons I suggest we ignore this bogus warning by adding the following line to the flake8 configuration in tox.ini: `ignore = W503`
>
> I did some more digging and found out a few more things. The W503 bug is already fixed as it's added to the default ignore list but you have a ignore option configured in setup.cfg and if that's the case the default ignores aren't respected anymore. This is in my opinion pretty stupid behavior but a flake8 thing I can't do anything about. That means though that if you specify a ignore list you have to list all default ignores as well. So I updated the list in setup.cfg and now the tests pass without problems.

**Comment by ailjushkin** [comment]
Thank you very much indeed, I'm indeed using the setup file and I didn't list basic defaults. Thanks.

**Comment by sigmavirus24** [comment]
With #502 merged, I'm closing this as it will be fixed in the next release.
