### ISSUE TITLE
Metaclass __new__ method should have mcs as first argument, not cls

### ISSUE THREAD

**Issue by karyon** [PyCQA/pycodestyle#503]
in [this class](https://github.com/fsr-itse/EvaP/blob/0ec953b4f57b298667494c493a0b0f60f55ff244/evap/evaluation/meta.py#L11), pylint told me that the first argument to `__new__` should be `mcs`, so i changed it. Afterwards, pycodestyle told me it should be `cls`, which i think is wrong.

**Comment by sigmavirus24** [comment]
I disagree. For reference, [this section of PEP-0008](https://www.python.org/dev/peps/pep-0008/#function-and-method-arguments) tells us that any class method should use `cls` to indicate that it's receiving a class object as a parameter. [This section of PEP-0008](https://www.python.org/dev/peps/pep-0008/#designing-for-inheritance) also says:

> However, notwithstanding this rule, 'cls' is the preferred spelling for any variable or argument which is known to be a class, especially the first argument to a class method.

And the first argument to `__new__` is known to be a class object. Thus, pycodestyle is correct. pylint is unlikely to change that requirement and as such, I'd suggest you silence one of the two tools.

**Comment by NeilGirdhar** [comment]
FYI: https://github.com/PyCQA/pylint/issues/2028
