### ISSUE TITLE
limiting checking to an older version

### ISSUE THREAD

**Issue by brianjmurrell** [PyCQA/pycodestyle#505]
If I have, say, version 1.5.7 of pep8 installed but I only want to use the rules that were in a previous version, say 1.0.1, is there any way (i.e. option, environment, etc.) to do this, short of installing the older version?  I don't want to install the older version because the use-case for using the old version is intermittent.

**Comment by IanLee1521** [comment]
No, there isn't any record (out side of git itself) of the rules from a previous version.

This would be akin to trying to have a "previous version" of the PEP-8 document that you wanted to know the rules of.

**Comment by brianjmurrell** [comment]
Ahhh.  Pity.  I had hoped each rule was tagged with a version so as to allow this sort of thing.

Thanks for the quick response.

**Comment by jayvdb** [comment]
@brianjmurrell , you could build documentation around which version each rule was added and modified.  The history of https://github.com/PyCQA/pycodestyle/commits/master/docs/intro.rst will give you most of the information you need to build the list 95% correctly. e.g. https://github.com/PyCQA/pycodestyle/commit/2d072332abb69ba024329ea333954998be280221 was very likely released in v1.6 according to the tags at the top of that github page.
