### ISSUE TITLE
Update CONTRIBUTING to describe developer setup

### ISSUE THREAD

**Issue by IanLee1521** [PyCQA/pycodestyle#521]
Add step by step guide (with links) to getting started as a developer. In particular, the following instructions (at minimum) should be documented:

* Fork and clone repo
* Create virtualenv
* Install `tox`
* Run test suite locally with tox

**Comment by vodik** [comment]
I got this half done but I'm really struggling with English and noisy background. I'll push this one up in the evening when things are calmer.

**Comment by sigmavirus24** [comment]
Please put this into a CONTRIBUTING file instead of the README.

**Comment by vodik** [comment]
Okay, will do.

**Comment by IanLee1521** [comment]
Agreed. As I thought about it more realized that contributing is a better place.

**Comment by daspecster** [comment]
This should be all set from #566 right?

**Comment by sigmavirus24** [comment]
Looks like it.
