### ISSUE TITLE
Disable pep8 entry point in pep8 PyPI package

### ISSUE THREAD

**Issue by IanLee1521** [PyCQA/pycodestyle#544]
Based on the discussion in https://github.com/PyCQA/pycodestyle/issues/466#issuecomment-177691447, towards the end of this year the `pep8` entry point in the `pep8` PyPI package should be replaced with a stub, simply stating that the `pycodestyle` package is the new package and entry point which should be used instead.

``` bash
pip uninstall pep8
pip install pycodestyle
pycodestyle ...
```

**Comment by sigmavirus24** [comment]
I think that timeline needs to be shifted. The deprecation didn't really start until very recently. It should be shifted to adjust.

**Comment by jayvdb** [comment]
I dont see any explicit mention of semver for pep8 / pycodestyle, but it is worth considering that doing this would require a major release under semver.

So, could this planned stub be pep8 2.0 ?
If not, this will break old versions of other software that explicitly said they depend on `pep8>1,<2`.
It is likely that most of your intended goals of stubbing pep8 will be obtained by calling it `2.0`.

Or just leave pep8 1.x alone, to die a slow death, readily available to people who need it, but most users will move with the front-end tools which adopt pycodestyle fairly promptly.

**Comment by IanLee1521** [comment]
I would be reasonably comfortable with that approach. -- Leaving pep8 1.7.1 to be the final release to wither on the vine. Depends on how big a hammer @gvanrossum wants me to take to that old name ;)

**Comment by sigmavirus24** [comment]
I never understood the request to be that of "break existing software depending on a package". More, transition to a new name and let the old project die all software's slow eventual heat death. Will someone still be using pep8 1.4.x on Python 2.6 thanks to $SOFTWARE_VENDOR in 30 years? Sure. That's not our fault though.

**Comment by warsaw** [comment]
I'm comfortable with that approach too.  It may take a little time for reverse dependencies to catch up to the new goodness of pycodestyle, but in the meantime, let's keep pep8 functioning no worse than it is today.  Eventually it'll just bitrot away.

**Comment by hugovk** [comment]
Just a note that pycodestyle has overtaken pep8 in pip installs, with about two times as many. 

pycodestyle is also ~55% Python 3.x compared to pep8's ~30%. 

For last month:

## pep8

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  69.32% |        262,391 |
| 3.6            |  13.24% |         50,120 |
| 3.5            |   9.79% |         37,039 |
| 3.4            |   6.35% |         24,021 |
| 2.6            |   0.57% |          2,156 |
| 3.3            |   0.44% |          1,671 |
| 3.7            |   0.27% |          1,024 |
| 3.2            |   0.02% |             79 |
| None           |   0.01% |             23 |
| **Total** |  |       **378,524** |

## pycodestyle

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  44.93% |        359,668 |
| 3.6            |  31.20% |        249,772 |
| 3.5            |  15.74% |        125,981 |
| 3.4            |   6.71% |         53,737 |
| 3.3            |   0.60% |          4,776 |
| 3.7            |   0.39% |          3,103 |
| 2.6            |   0.37% |          2,955 |
| 3.2            |   0.05% |            421 |
| 3.8            |   0.00% |              8 |
| None           |   0.00% |              4 |
| **Total** |  |       **800,425** |



(eg. from `pypinfo --start-date -48 --end-date -21 --percent --pip --markdown pep8 pyversion`)

**Comment by sigmavirus24** [comment]
@hugovk I'm wondering how download statistics impacts a decision to release a version of pep8 that doesn't have the command-line entry-point `pep8`.

**Comment by sigmavirus24** [comment]
All that said, I think we're all in agreement that we shouldn't break the `pep8` package or CLI, so I'm closing this.

**Comment by hugovk** [comment]
👍 

Just some stats to show that "Eventually it'll just bitrot away" is underway nicely, and dependencies are by and large moving over to the new goodness of pycodestyle.
