### ISSUE TITLE
Backward compatibility for imports?

### ISSUE THREAD

**Issue by warsaw** [PyCQA/pycodestyle#549]
I'm all in favor of the rename to pycodestyle, but I wonder if it wouldn't have been better to add a backward compatible and deprecated hook for `import pep8`?  I know at least that the `flake8_respect_noqa` package is broken by the change because it can't `import pep8`.  Having a temporary deprecated hook would at least give clients of the old pep8 namespace a chance to update their code.

I'm considering adding this for the Debian package of the new pycodestyle version.  Is there a reason why I shouldn't do this?

**Comment by warsaw** [comment]
Oh, hmm. this might be a dupe of #544

**Comment by sigmavirus24** [comment]
Import hooks are bad magic things that break projects relying on certain behaviours of modules. Do you know of a good way to do this in a regular sdist/whl that won't annoy you/others as downstreams and will not do weird things during installation?

**Comment by warsaw** [comment]
Well, I'm not sure there is a *good* way, but there are ways short of import hooks (sorry I used that term, I should have used "hack" :)

I wonder if something as simple as including a pep8.py module for a short time, which contained only:

```
from pycodestyle import *
import warnings
warnings.warn("import pep8 is deprecated; use pycodestyle instead", DeprecationWarning)
```

**Comment by IanLee1521** [comment]
So, I had originally thought of doing something like this as the migration, but decided to not try to keep both paths alive in the same package.

The biggest reason why is getting into issues like: "what config section are users expected to use? `[pep8]` or `[pycodestyle]`?", "what should the user config files be named? `~/.config/pep8` or `~/.config/pycodestyle`?" And a few other things that I'm blanking on at the moment.

Instead, I left the pep8 package on PyPI and started a new [1.7.x branch here](https://github.com/PyCQA/pycodestyle/compare/1.7.0...release/1.7.x) to track the changes that amount to what you suggested (specifically: https://github.com/PyCQA/pycodestyle/blob/release/1.7.x/pep8.py#L2123).

That said, I'm realizing I forgot to actually tag and push the 1.7.1 release which was meant to include that warning... I'll give this thread a chance to respond, and then go ahead and do that tag later this week if there are no issues.

**Comment by warsaw** [comment]
I only noticed this because flake8_respect_noqa started to fail in a tox environment for Mailman 3.  Honestly, if it all just works from PyPI, I'll be happy.  I'm less concerned about the confirmation sections although I can see your point about backward compatibility for that.  Maybe it makes more sense to leave the PyPI pep8 tool untouched and just start a new one for pycodestyle?  This lets end users just decide when it's best for them to switch over.  (Maybe you've already done this?  In which case, why does it fail in a fresh tox/pypi install when the dependency hasn't changed?)

FWIW, I'm leaning on leaving pep8 in Debian alone and creating a new source package for pycodestyle.

**Comment by sigmavirus24** [comment]
@warsaw The reason `flake8_respect_noqa` fails in a new virtualenv fails because you're likely using `flake8 2.6.0` which has switched over directly to `pycodestyle`. `flake8_respect_noqa` was expecting flake8 to always install `pep8`for it instead of explicitly declaring a dependency on `pep8` which it should have been doing and should continue to do for as long as it wants to use that.

**Comment by IanLee1521** [comment]
Seems like `flake8_respect_noqa` needs to either update the [`setup.py` file](https://github.com/spookylukey/flake8-respect-noqa/blob/master/setup.py#L33) with different versions of flake8 or needs to explicitly require `pep8` to be installed.

> Maybe it makes more sense to leave the PyPI pep8 tool untouched and just start a new one for pycodestyle?

That's what the current state is:

* https://pypi.python.org/pypi/pep8
* https://pypi.python.org/pypi/pycodestyle

**Comment by warsaw** [comment]
See also https://github.com/spookylukey/flake8-respect-noqa/pull/2

**Comment by IanLee1521** [comment]
So I believe the right place for this issues is the flake8-respect-noqa package, and so I've made my comments over there on how that package can better handle the pep8 -> pycodestyle transition.

**Comment by IanLee1521** [comment]
@warsaw -- btw...

> FWIW, I'm leaning on leaving pep8 in Debian alone and creating a new source package for pycodestyle.

I think this is reasonable and I was curious how Debian would want to handle this. At some point you might want to retire the pep8 package, but that might be a ways away.

Also, cc/ @ncoghlan, if you might be able to forward this on the the RedHat `python-pep8` maintainer, that would be great. E.g. maybe need a `python-pycodestyle` package?

**Comment by warsaw** [comment]
@IanLee1521 I haven't yet decided whether to keep the pep8 package for Debian Stretch.  There's good arguments on both sides.  We have time so I think we'll just see how it plays out.

**Comment by ncoghlan** [comment]
Thanks for the heads up @IanLee1521 - I've added a reference back to this discussion to the Fedora pycodestyle package review request: https://bugzilla.redhat.com/show_bug.cgi?id=1342839#c10
