### ISSUE TITLE
How do I make this snippet PEP8 compliant?

### ISSUE THREAD

**Issue by controversial** [PyCQA/pycodestyle#554]
It seems that whatever I do, this snippet can't pass PEP8.
```python
if (parts.scheme not in ("https", "http") or
    parts.netloc not in ("github.com", "www.github.com") or
    len(parts.path.strip("/").split("/")) != 2):
    pass
```

As it is, I get `E129 visually indented line with same indent as next logical line`.

If I move the `):` somewhere else, I can't find any indentation levels that it's happy about. If it's like this
```python
    len(parts.path.strip("/").split("/")) != 2
    ):
```
then I get `E125 continuation line with same indent as next logical line`. Anywhere else, `closing bracket does not match visual indentation`.

If I remove the parentheses, there's nowhere I can put my statements without having `unexpected indentation` or `indentation is not a multiple of four`.

It would seem I can't win! What's the correct formatting in this scenario?

**Comment by The-Compiler** [comment]
The `)` isn't the problem - the problem is that you have multiple lines in your `if` which are indented the same like the body of the `if`. pep8 (the document) recommends further indenting them:

```
if (parts.scheme not in ("https", "http") or
        parts.netloc not in ("github.com", "www.github.com") or
        len(parts.path.strip("/").split("/")) != 2):
    pass
```

**Comment by controversial** [comment]
Thanks a lot, that fixes it!
