### ISSUE TITLE
pycodestyle.py violates PEP8 ;)

### ISSUE THREAD

**Issue by DeepSpace2** [PyCQA/pycodestyle#558]
Not really an issue, I just found it ironic that `pycodestyle.py` violates PEP8 (a local import in function _main) 

    def _main():     
        """Parse options and run checks on Python source."""
        import signal

**Comment by sigmavirus24** [comment]
I don't think this is an issue. The signal import is only necessary when running pycodestyle, e.g., `python pycodestyle.py ...`. If you're importing pycodestyle for use in a different project (as projects like Flake8 do) then there's no need to import signal. PEP-0008 is a *guideline* not a strict set of rules, so I don't see any problem with this.
