### ISSUE TITLE
Is it possible to check that 'self' is first argument in an instance method?

### ISSUE THREAD

**Issue by mbanders** [PyCQA/pycodestyle#560]
From pep8:

> Always use self for the first argument to instance methods.

So I thought pycodestyle would have complained about code like this:

```py
class Kitten():
    def change_name(elf, name):
        elf.name = name
```

But no message is printed for using a name other than `self`.

**Comment by sigmavirus24** [comment]
Its not possible for pycodestyle to do this at the moment. If, however, you're using Flake8, you can install [pep8-naming](https://github.com/PyCQA/pep8-naming) to get a check like this (and a few others).

**Comment by hoylemd** [comment]
I don't think this is necessarily even something it should do.  After all, you can have a function defined in class scope that isn't intended to be an instance method:

```
class Kitten(object):
    def complete_name(name):
        return "{} the cute kitty cat"    

    def change_name(self, name):
        self.name = name
        self.full_name = complete_name(name)
```

**Comment by sigmavirus24** [comment]
@hoylemd those are typically, however, decorated with `@staticmethod`.

**Comment by sigmavirus24** [comment]
@hoylemd also, you'd need to at least do `Kitten.complete_name` in that case.

**Comment by sigmavirus24** [comment]
Woops. I meant to close this yesterday.

**Comment by hoylemd** [comment]
@sigmavirus24 Huh. I thought that worked? I must have been thinking of using `def` to make named lambdas.
