### ISSUE TITLE
[pycodestyle] section not getting picked up in tox.ini

### ISSUE THREAD

**Issue by daspecster** [PyCQA/pycodestyle#563]
Unless I've missed updating something important, it appears that you still have to mark the section as `[pep8]` instead of `[pycodestyle]`?

There's a Travis build and PR here as an example.
https://github.com/GoogleCloudPlatform/gcloud-python/pull/2020

**Comment by sigmavirus24** [comment]
See also https://github.com/PyCQA/pycodestyle/issues/550. This is fixed in master.
