### ISSUE TITLE
Debian/Ubuntu with pycodestyle name

### ISSUE THREAD

**Issue by carlosperate** [PyCQA/pycodestyle#565]
The readme file indicates there is a debian package, however as far as I've been able to find it only exists for the old pep8 name. Is there a package coming with the new name?

Since it seem like the package is maintained by the "pep8 team" (https://launchpad.net/pep8) I assume this would be the correct place to ask about this?

**Comment by sigmavirus24** [comment]
This is not the correct place. None of the people in that LaunchPad team are actually involved in the development of pycodestyle. They merely package it. You'll probably be interested in [this thread from debian-python](https://osdir.com/ml/debian-python/2016-06/msg00041.html).

**Comment by carlosperate** [comment]
Apologies then, and thanks for pointing me to the right direction.

**Comment by sigmavirus24** [comment]
No need to apologize. I understand that this is all confusing. :)
