### ISSUE TITLE
E127 on slightly modified PEP-8 approved example (multiline with)

### ISSUE THREAD

**Issue by pquentin** [PyCQA/pycodestyle#569]
I took the multiline with statement from PEP-8 and tested a few variations. I only get an error when the statement is inside a function and preceded by another statement. This seems related to #316 and #256. git bisect confirms: the first bad commit is 974748fd9a0ecdd494cdc51aeb16c54d38256d58.
## Steps to reproduce

Run pycodestyle on:

```
def f1():
    print('foo')
    with open('/path/to/some/file/you/want/to/read') as file_1, \
         open('/path/to/some/file/being/written', 'w') as file_2:
        file_2.write(file_1.read())


def f2():
    with open('/path/to/some/file/you/want/to/read') as file_1, \
         open('/path/to/some/file/being/written', 'w') as file_2:
        file_2.write(file_1.read())

print('foo')
with open('/path/to/some/file/you/want/to/read') as file_1, \
     open('/path/to/some/file/being/written', 'w') as file_2:
    file_2.write(file_1.read())
```
## Result

`test.py:4:10: E127 continuation line over-indented for visual indent`
## Expected

No error, or at least the same behavior between all three versions. Before 974748fd9a0ecdd494cdc51aeb16c54d38256d58, pycodestyle reported E126 errors for the other two variations.

**Comment by plammens** [comment]
I think this applies to any statement enclosed in a scope when preceded by at least one statement or nonempty expression, where the continuation line is indented by more than 4 spaces

### Examples that don't produce E127

```python
assert 123456 == \
       123456
```
```python
pass
assert 123456 == \
       123456
```
```python
def spam():
    # this comment is not a statement or expression
    assert 123456 == \
           123456
    pass
```

### Examples that do produce E127 (and shouldn't)

```python
def foo():
    pass
    raise 123 + \
          123
```
```python
class Eggs:
    pass
    assert 123456 == \
           123456
```
```python
with open('test.txt', 'w') as file:
    1 + 1
    assert True \
           and True
```
```python
if True:
    pass
    assert 123456 == \
           123456
```
