### ISSUE TITLE
Notify users that "pep8" was renamed to "pycodestyle"

### ISSUE THREAD

**Issue by Ede123** [PyCQA/pycodestyle#572]
There are many places were there is still outdated information refering to "pep8" instead of "pycodestyle" making no mention of the name change (#466, #481) which can be quite misleading.

For example I just installed "pep8" unaware of the fact and wondered why it was outputting a lot of W503s [when it shouldn't](#499). That's when I realized the project had been renamed and I had installed the outdated pep8 version 1.7.0 instead of the current pycodestyle 2.0.0

I'm not familiar with PyPI and don't know if there is a possibility to deprecate packages but it would be a huge help for new users if the name change was announced prominently at [[1]](https://pypi.python.org/pypi/pep8) and [[2]](http://pep8.readthedocs.io/).
An updated package of pep8 with a deprecation warning might be yet another option if that's not too much to ask.

[1] https://pypi.python.org/pypi/pep8
[2] http://pep8.readthedocs.io/

**Comment by hugovk** [comment]
13 months later and I've only just noticed the name change and am still on the old pep8 1.7.0. I've updated (or tried to update) pep8 many times, and a warning would have helped me.

A prominent note has been added to [[2]](https://pep8.readthedocs.io/):

> Note
>
> This package used to be called pep8 but was renamed to pycodestyle to reduce confusion. Further discussion can be found in the issue where Guido requested this change, or in the lightning talk at PyCon 2016 by @IanLee1521: slides video.

Thanks! 

It'd be great to also put one at [[1]](https://pypi.python.org/pypi/pep8) as well.

I've created PR https://github.com/PyCQA/pycodestyle/pull/690 to issue a warning in pep8.

**Comment by hugovk** [comment]
On further investigation, it looks like the warning has already been done in https://github.com/PyCQA/pycodestyle/commit/d4a60037be95b4b5f84a040bc40ce2ca703640bb in in May 2016 in the release/1.7.x branch, but not yet released.

Please could we have a new release of pep8 with that warning? Thank you!

**Comment by gsnedders** [comment]
See also https://github.com/PyCQA/pycodestyle/issues/602 and https://github.com/PyCQA/pycodestyle/issues/603

**Comment by sigmavirus24** [comment]
1.7.1 was released with a runtime warning

**Comment by hugovk** [comment]
Thanks! I think this issue can be closed now.


```
$ pep8 .
/usr/local/lib/python2.7/site-packages/pep8.py:2124: UserWarning:

pep8 has been renamed to pycodestyle (GitHub issue #466)
Use of the pep8 tool will be removed in a future release.
Please install and use `pycodestyle` instead.

$ pip install pycodestyle
$ pycodestyle ...
```
