### ISSUE TITLE
flake8-docstrings D100 issue while checking file passed to stdin

### ISSUE THREAD

**Issue by XAMeLeOH** [PyCQA/pycodestyle#577]
# Problem description
While using flake8 package to validate the code which uses pydocstyle or pep257 as backend and combination of flake8-docstrings and pycodestyle, docstrings don't validate correctly.

This is due to absent ability of backend (pydocstyle or pep257) work with content from stdin. Because of this pycodestyle provides helper function named stdin_get_value to avoid this problem.

But in case of using flake8 there are several plugins can read from stdin, so when it's stdin_get_value's turn there is no data in stdin.

# Testing
To test the issue you have to install `flake8` and `flake8-docstrings` packages, which will install dependent package including `pycodestyle`.

After the package will installed, create sample file (`/tmp/testcase.py`):

```
"""Module represent something."""


def main():
    print("Main")

if __name__ == "__main__":
    main()
```

While checking the file in regular way (`flake8 /tmp/testcase.py`) should be displayed lines below:

```
stdin:4:1: D103 Missing docstring in public function
```

The same file will give different result in case of passing it to stdin (`flake8 - < /tmp/testcase.py`):

```
stdin:1:1: D100 Missing docstring in public module
```

This is because `pydocstyle` gets an empty string as a source.

**Comment by sigmavirus24** [comment]
What version of Flake8 and flake8-docstrings are you using? I think you've reported this against the wrong project.

**Comment by XAMeLeOH** [comment]
$ pip freeze | grep flake
    flake8==3.0.4
    flake8-docstrings==1.0.2
    pyflakes==1.2.3

Yes, it looks so. I think I should report the bug to the flake8-docstring project. Perhaps, it's already fixed in current version. Sorry for inconvenience.

**Comment by sigmavirus24** [comment]
@XAMeLeOH no need to apologize :)

**Comment by IanLee1521** [comment]
Yes @XAMeLeOH, thank you getting as far as reporting. Most times people don't try to do that part!
