### ISSUE TITLE
E999 SyntaxError: invalid syntax - missing from documentation page

### ISSUE THREAD

**Issue by Integralist** [PyCQA/pycodestyle#584]
I've noticed the error `E999 SyntaxError: invalid syntax`, but it doesn't seem to be documented any where.

I've checked here: http://pep8.readthedocs.io/en/latest/intro.html#error-codes but there's no mention of it.

Is there any reason for that, or was it just missed accidentally?

Thanks

**Comment by IanLee1521** [comment]
Can you provide a sample of how you're getting the E999 error? That doesn't appear to be an Error code we have in pycodestyle: https://github.com/PyCQA/pycodestyle/blob/master/pycodestyle.py

**Comment by sigmavirus24** [comment]
@Integralist how are you running pycodestyle?

**Comment by Integralist** [comment]
So we're using Flake8 to lint our Python and it's being run inside of a CI that I believe doesn't have the version of Python our application is using † and so it errors like so:

```
2016-10-28 04:19:46.219 running flake8 for lib/python...
2016-10-28 04:19:47.891 /var/lib/jenkins/workspace/mono/lib/python/cap/services/utils.py:50:14: E999 SyntaxError: invalid syntax
```

Hence we added `# flake8: noqa: E999` to resolve the issue as we know it's not a syntax error

† to explain: we have a mono repo, where each directory is a different service, and our application has moved some of its modules into a 'shared' directory so other apps can use that code. The problem there is that we have two CI's; one CI uses Docker to run our app and its tests/linter etc with the relevant and correct environment √ the other CI doesn't use Docker and uses Python 2 instead of Python 3 which our app uses and it runs its own integration tests against all the 'services' (i.e. directories within our mono repo)

**Comment by IanLee1521** [comment]
I can't seem to find what is issuing that error code... It's not Pycodestyle (https://github.com/PyCQA/pycodestyle/search?q=E999&type=Code&utf8=✓) though, so I'm going to go ahead and close this.

I believe you're seeing this from flake8 itself: https://github.com/PyCQA/flake8/blob/master/src/flake8/checker.py#L499

**Comment by Integralist** [comment]
OK no problem @ianlee1521 

do you happen to know who I should contact regarding the E999 code? 

As you've shown, it's being reported by flake8 but I couldn't find any documentation provided by flake8 that details it

**Comment by sigmavirus24** [comment]
@Integralist What do you think of https://gitlab.com/pycqa/flake8/merge_requests/130 ?

**Comment by Integralist** [comment]
Thank you. That's very much appreciated :-)

**Comment by sigmavirus24** [comment]
Happy to help @Integralist :)

**Comment by pradeepkalsyan** [comment]
# I am creating my own simple metaclass to intercept the class creation behaviour in python.
class mytype(type):
    def __new__(meta, clsname, bases, methods):
        print("Creating:", clsname)
        print("Base:", bases)
        print("Methods:", list(methods))
        return super().__new__(meta, clsname, bases, methods)

# here we get the syntax error for metaclass keyword.
class base(metaclass=mytype):
    pass
