### ISSUE TITLE
--format=<custom> example

### ISSUE THREAD

**Issue by spaceone** [PyCQA/pycodestyle#585]
The manpage and --help output should print one example for --format with a custom style. I can't find how to use this.

**Comment by spaceone** [comment]
```
1747             print(self._fmt % {
1748                 'path': self.filename,
1749                 'row': self.line_offset + line_number, 'col': offset + 1,
1750                 'code': code, 'text': text,
1751             })
```

--format '%(path)s %(row)s %(code)s'

**Comment by sigmavirus24** [comment]
The [documentation](https://pycodestyle.readthedocs.io/en/latest/intro.html#example-usage-and-output) very clearly explains this.
