### ISSUE TITLE
Except foo, bar:

### ISSUE THREAD

**Issue by spaceone** [PyCQA/pycodestyle#594]
If would be nice if `except foo, bar:` would be detected and suggested to change into `except foo as bar`.

**Comment by sigmavirus24** [comment]
I don't think this is something that will be a reliable check. Here's why:

Many projects still refuse to add Python 3 support, so if you have two exception classes, e.g., `Exception1` and `Exception2` then on Python 2 it's syntactically valid to 

```py
except Exception1, Exception2:

**Comment by spaceone** [comment]
No, this is syntactically invalid!
you can do (in python2 and 3):
`except (Exception1, Exception2):`
`except (Exception1, Exception2), exc:`
`except (Exception1, Exception2) as exc:`

but if you do:
`except Exception1, Exception2:`
python will reassign the instance of Exception1 to the name Exception2.

**Comment by spaceone** [comment]
Here is the proove
```
>>> try:
...  raise ValueError('foo')
... except KeyError, ValueError:
...  print 'ValueError catched'
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ValueError: foo
```
VS
```
>>> try:
...  raise ValueError('foo')
... except (KeyError, ValueError):
...  print 'ValueError catched'
... 
ValueError catched
```

**Comment by asottile** [comment]
I believe this is out of scope for stylistic suggestions for pycodestyle -- fortunately, this is detected by pyflakes:

```console
$ pyflakes t.py
t.py:3:17: invalid syntax
except Exception, BaseException:
                ^
```
