### ISSUE TITLE
Exclude option no longer parsed from tox file

### ISSUE THREAD

**Issue by evenicoulddoit** [PyCQA/pycodestyle#596]
Passing the `--exclude=` parameter to the execute works, but the `tox.ini` support for exclude seems to have been removed.

**Comment by sigmavirus24** [comment]
@evenicoulddoit could you perhaps provide your `tox.ini` section and what version of the software you're using. Without either, neither of us are going to try to divine the magic combination that leads to the behaviour you're seeing.

**Comment by evenicoulddoit** [comment]
Hah - sorry, I apologise

I just upgraded to `pycodestyle==2.0.0` and my `tox.ini` was:

```ini
[pycodestyle]
exclude = migrations,node_modules,static,app/
ignore  = E731
```

**Comment by sigmavirus24** [comment]
@evenicoulddoit so you have that config and you're running just `pycodestyle` and it's picking things up from one or more of those places, yes? In that case, this should be easy to track down. Thanks for providing the extra context.

**Comment by evenicoulddoit** [comment]
@sigmavirus24 Running `pycodestyle .` from project root, and running `pycodestyle . --exclude=migrations...` works - yes

**Comment by sigmavirus24** [comment]
@evenicoulddoit did you try running pycodestyle with increased verbosity? (e.g., `pycodestyle -vv .`) that should tell you if it even sees that option. I also wonder if you run into this with 2.1.0 (which was released yesterday or the day before)

**Comment by evenicoulddoit** [comment]
The output of `pycodestyle -vv .` is:

```
local configuration: in /<pwd>
directory .

checking <file>
xxxxxxxxxxxx
...
```

**Comment by evenicoulddoit** [comment]
Same issue for 2.1.0

**Comment by sigmavirus24** [comment]
So it's also not picking up your --ignore setting then, yet?

I just did this:

```
~ ❯❯❯ virtualenv .pycodestyle
~ ❯❯❯ cd .pycodestyle
~/.pycodestyle ❯❯❯ source bin/activate
(.pycodestyle) ~/.pycodestyle ❯❯❯ pip install pycodestyle
(.pycodestyle) ~/.pycodestyle ❯❯❯ cat > tox.ini <<EOF
> [pycodestyle]
> exclude = foo,bar,bogus,baz,lib,bin,include
> ignore = E731
> EOF
(.pycodestyle) ~/.pycodestyle ❯❯❯ python -m pycodestyle -vv .
local configuration: in ~/.pycodestyle
  exclude = foo,bar,bogus,baz,lib,bin,include
  ignore = E731
directory .
(.pycodestyle) ~/.pycodestyle ❯❯❯ cat > example.py <<EOF
> a=1
> EOF
(.pycodestyle) ~/.pycodestyle ❯❯❯ python -m pycodestyle -vv .
local configuration: in ~/.pycodestyle
  exclude = foo,bar,bogus,baz,lib,bin,include
  ignore = E731
```

Even if I update the exclude list to have a trailing `/` like your example, I don't see different behaviour.

Are there any other details you can provide?
directory .
checking ./example.py
a=1
./example.py:1:2: E225 missing whitespace around operator

**Comment by asottile** [comment]
I cannot reproduce this -- if this is still a problem please either link a repository which demonstrates this problem or include the full unredacted output of `pycodestyle -vv` and the contents of your `tox.ini` file
