### ISSUE TITLE
format() arguments aren't ambiguous

### ISSUE THREAD

**Issue by nchammas** [PyCQA/pycodestyle#597]
What's ambiguous about `l`?

```python
if __name__ == '__main__':
    print(
        "Your current limit is {l}."
        .format(l=9000)
    )
```

```sh
$ pycodestyle test.py 
test.py:4:17: E741 ambiguous variable name 'l'
```

This only started happening in pycodestyle 2.1.0. I'm running Python 3.5.2.

**Comment by spaceone** [comment]
"l" looks like "1"

**Comment by nchammas** [comment]
That's true. I suppose in a general sense it could be ambiguous, though in the above example that's obviously not that case. Perhaps it's too much to have pycodestyle make exceptions for certain situations, since I imagine that would complicate the tool needlessly.

I'll close this if the maintainers confirm this is intended behavior.

**Comment by sigmavirus24** [comment]
@nchammas it is the intended behaviour and implements a very specific portion of PEP-0008 regarding single letter variables that may bare a resemblance to other characters.
