### ISSUE TITLE
Update v1.7.x README to point to pycodestyle

### ISSUE THREAD

**Issue by IanLee1521** [PyCQA/pycodestyle#603]
From https://github.com/PyCQA/pycodestyle/issues/466#issuecomment-260721352

> https://pypi.python.org/pypi/pep8 says nothing about the name change, hence it'd be easy to conclude 1.7.0 is the latest version.

**Comment by JonathanDensil** [comment]
@IanLee1521 I am new to contributing to github projects. Would it be possible for you to walk me through the process in resolving this issue please? I read the contributing doc and am guessing I would first have to fork this project and then install virtualenv. But after that, how would I go about editing the pep8 documentation?

**Comment by nicktimko** [comment]
What behavior would be desired? I could imagine a couple:

1. Do nothing (other than change the package metadata to suggest pycodestyle instead).
1. Warn that the pep8 package no longer is updated but continue to install 1.7.0
1. Warn and redirect/install the latest version of pycodestyle (Breaks version pinning, but if someone has the version pinned, this shouldn't be an issue anyways. Releasing it as 2.0 would exempt future-thinking people that might have done `pep8>1.7,<=1.8`)
1. Warn and turn installing into a no-op.
1. Error (disrupting the rest of the install process to make it very obvious).

Maybe phases of some combination?

**Comment by hugovk** [comment]
pep8 1.7.1 has been released which gives a warning:

```
$ pep8 .
/usr/local/lib/python2.7/site-packages/pep8.py:2124: UserWarning:

pep8 has been renamed to pycodestyle (GitHub issue #466)
Use of the pep8 tool will be removed in a future release.
Please install and use `pycodestyle` instead.

$ pip install pycodestyle
$ pycodestyle ...
```

👍
