### ISSUE TITLE
`StyleGuide.ignore_code` can't decide if `select` is a string or an iterable

### ISSUE THREAD

**Issue by AdamWill** [PyCQA/pycodestyle#608]
This is how `StyleGuide.ignore_code()` looks ATM:

        if len(code) < 4 and any(s.startswith(code)
                                 for s in self.options.select):
            return False
        return (code.startswith(self.options.ignore) and
                not code.startswith(self.options.select))

note the first part expects `self.options.select` to be an iterable, but the second part expects it to be a string.

**Comment by AdamWill** [comment]
The first part in its entirety is actually rather odd. In what circumstances does it ever trigger? i.e. in what circumstances is `len(code)` ever `< 4`? AFAICS it should always be at least 4, unless someone registers a check with a non-standard code.

**Comment by sigmavirus24** [comment]
`code.startswith` can take a `tuple` or a `str` so this seems to be a frivolous issue.

> The first part in its entirety is actually rather odd. In what circumstances does it ever trigger?

Codes tend to be 4 characters. So if it's less than that we check for a conflict of select and the code. Otherwise we check that the code is ignored and that it wasn't explicitly selected.

**Comment by sigmavirus24** [comment]
Happy to help
