### ISSUE TITLE
Add to docs that you can execute multiple grepped inputs

### ISSUE THREAD

**Issue by BoltzmannBrain** [PyCQA/pycodestyle#609]
Not necessarily an issue, but this was a pain for me to figure out and would be useful in the docs (perhaps as an example usage): http://stackoverflow.com/a/41513633/3765905

**Comment by sigmavirus24** [comment]
unix style piping of output from commands has nothing to do with pep8. You can have as many pipes in there as you want, you also don't need to use two greps, but that's besides the point.

I'm not sure that particular example usage would be worth including in the docs. It's too far removed from the actual use case. Thanks for the suggestion though!

**Comment by IanLee1521** [comment]
If you do think of a way we could include it though, probably would be best as a pull request so we can discuss any actual change. Thanks though!
