### ISSUE TITLE
Missing git tag for 2.3.1 release

### ISSUE THREAD

**Issue by felixonmars** [PyCQA/pycodestyle#623]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by jayvdb** [comment]
Interesting https://github.com/PyCQA/pycodestyle/releases still shows 2.2.0 as the latest release, while 2.3.1 appears after it.

**Comment by sigmavirus24** [comment]
@jayvdb please stop reviving long dead issues. `/releases` is not the same as `/tags`. `/releases` is a separate thing in GitHub which requires you to associate a tag with some markdown and binary files. If there's no release it is likely that Ian didn't have the time to generate that information.

**Comment by IanLee1521** [comment]
@jayvdb  -- This is now fixed. Cheers!
