### ISSUE TITLE
Option to convert all errors to warnings

### ISSUE THREAD

**Issue by MaxNoe** [PyCQA/pycodestyle#629]
This would be very helpfull for IDEs or e.g. vim plugins to distinguish between programming errors and style errors.

**Comment by sigmavirus24** [comment]
Most IDEs that I integrate with PyCodestyle or Flake8 (that I'm aware of) undertand the difference between a programming error in the file and a warning generated by a plugin. In my experience with vim plugins, Syntastic does a fantastic job of distinguishing betwen them.

People usually tend to want to treat warnings as errors in tooling like pycodestyle. That said, There are many cases where there's an `ENNN` that would map over `WNNN`.

So even if we wanted to allow people to treat one thing as another, we can't practically do that.

**Comment by timlegrand** [comment]
What about having a warning for --max-line-length > 79 and an error for --max-line-length > 89 ? The purpose of having both warning and errors levels is to match danger thresholds.

**Comment by ComfyDust** [comment]
FYI - When using VS Code this can be accomplished by adding

```
"python.linting.pycodestyleCategorySeverity.E": "Warning"
```

to your settings.
