### ISSUE TITLE
Imports inside functions not checked

### ISSUE THREAD

**Issue by behrtam** [PyCQA/pycodestyle#637]
Are imports inside functions ignored when checking for E402 because it is only about module level imports? Shouldn't there be an error for that?

```python
 1: a = 42
 2: import datetime
 3:
 4:
 5: def foobar():
 6:     import string
 7:     return string.ascii_lowercase[0]
 8: 
 9: 
10: import collections
```
```
$ pycodestyle  example.py
example.py:2:1: E402 module level import not at top of file
example.py:10:1: E402 module level import not at top of file
```

PEP8
> Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.

**Comment by sigmavirus24** [comment]
There are always exceptions. Occasionally imports can not exist at the top-level due to circular imports. I believe these are specifically ignored because of this, regardless of the document's wording.
