### ISSUE TITLE
The ignore option is ignored

### ISSUE THREAD

**Issue by behrtam** [PyCQA/pycodestyle#638]
It works to just ignore E741 but if I want to select all errors and warnings but ignore E741, I still see the errors.

Is the ignore option ignored (or overruled by select), so is the combination of select and ignore only possible with flake8 (since 3.x)? Or should this also work with pycodestyle?

```
$ pycodestyle .
./exercises/hexadecimal/example.py:8:5: E741 ambiguous variable name 'l'
./exercises/rectangles/example.py:79:9: E741 ambiguous variable name 'l'
./exercises/run-length-encoding/example.py:11:9: E741 ambiguous variable name 'l'
./exercises/run-length-encoding/example.py:12:21: E741 ambiguous variable name 'l'
./exercises/wordy/example.py:17:5: E741 ambiguous variable name 'l'

 $ pycodestyle --ignore=E741 .
 
$ pycodestyle --select=E,W --ignore=E741 .
./exercises/hexadecimal/example.py:8:5: E741 ambiguous variable name 'l'
./exercises/rectangles/example.py:79:9: E741 ambiguous variable name 'l'
./exercises/run-length-encoding/example.py:11:9: E741 ambiguous variable name 'l'
./exercises/run-length-encoding/example.py:12:21: E741 ambiguous variable name 'l'
./exercises/wordy/example.py:17:5: E741 ambiguous variable name 'l'

$
```
code used: https://github.com/exercism/xpython
pycodestyle: 2.3.1

**Comment by behrtam** [comment]
Just tried flake8, which surprisingly never reports E741 ... I thought it's using pycodestyle under the hood.

```
$ flake8 .

$ flake8 --select=E,W .

$ flake8 --ignore=E741 .

$ flake8 --select=E741 .

$ flake8 --select=E,W --ignore=E741 .

$ flake8 --ignore=W .

$
```

**Comment by sigmavirus24** [comment]
I do not believe this is a pycodestyle bug. Cheers

**Comment by sigmavirus24** [comment]
> Is the ignore option ignored (or overruled by select), so is the combination of select and ignore only possible with flake8 (since 3.x)? Or should this also work with pycodestyle?

Correct, Flake8 rewrote a lot of logic to make that combination possible. It's not something currently possible with pycodestyle and it's not clear that it will ever be possible.
