### ISSUE TITLE
Followed pep8 but got an "E402 module level import not at top of file"

### ISSUE THREAD

**Issue by uvchik** [PyCQA/pycodestyle#641]
I followed https://www.python.org/dev/peps/pep-0008/#module-level-dunder-names and got an `E402 module level import not at top of file`. Is this a bug or do I misunderstand something?

**Comment by sigmavirus24** [comment]
Please search for open *and* closed issues before opening new ones. Here are other issues discussing this same issue:

- #394 
- #398 
- #472 
- #589 

This is a limitation of the way pycodestyle works.
