### ISSUE TITLE
cProfile?

### ISSUE THREAD

**Issue by JulienPalard** [PyCQA/pycodestyle#645]
Have anyone tried running pycodestyle under cProfile?

I have hard times doing it: the `mod = inspect.getmodule(register_check)` returns the `cProfile` module, discovering no test function, any idea?

**Comment by asottile** [comment]
here's how I've done this in the past (just verified with a sample run)

```bash
python3 -m cProfile -o stats.pstats $(which pycodestyle) ...
gprof2dot stats.pstats -o stats.dot  # I'm using yelp-gprof2dot which has some fixes
dot -Tsvg -o stats.svg stats.dot
```
