### ISSUE TITLE
What is the latest stable release?

### ISSUE THREAD

**Issue by ilovezfs** [PyCQA/pycodestyle#660]
According to the GitHub releases page (https://github.com/PyCQA/pycodestyle/releases) the latest release is 2.2.0 (https://github.com/PyCQA/pycodestyle/releases/latest). But on PyPI it looks like 2.3.1 is being distributed as the latest version. Which version should we have in Homebrew for the stable spec of the pycodestyle formula?

**Comment by sigmavirus24** [comment]
GitHub releases are not the official release stream. PyPI is the official location of releases. That should be the canonical source for Homebrew (as it is for other downstreams).

**Comment by ilovezfs** [comment]
@sigmavirus24 thanks! It would be helpful to delete the published 2.2.0 release from GitHub to avoid confusion. Then 2.3.1 will automatically appear at the top of your releases list as expected.

See for example https://github.com/pyca/cryptography/releases

**Comment by sigmavirus24** [comment]
GitHub doesn't allow you to delete Releases. Maybe it can be done via the API but I don't have time for that at the moment. If others a confused about this, they'll search and find this.

**Comment by ilovezfs** [comment]
@sigmavirus24 the GUI does let you. If you go to https://github.com/PyCQA/pycodestyle/releases/tag/2.2.0 you should see a delete button in the upper right:

<img width="1011" alt="screen shot 2017-06-28 at 9 22 30 pm" src="https://user-images.githubusercontent.com/5268928/27671332-f40dd0be-5c47-11e7-8c36-625af0245658.png">

**Comment by IanLee1521** [comment]
I just went in and update the releases appropriately. @ilovezfs - take a look and make sure I didn't miss any?

Thanks!

**Comment by ilovezfs** [comment]
@IanLee1521 looks perfect. Thank you so much. This helps keep our livecheck system working smoothly. Everything is consistent now:

```
bash-4.4$ brew livecheck pycodestyle
pycodestyle (guessed) : 2.3.1 ==> 2.3.1
bash-4.4$ latest pycodestyle
2.3.1
bash-4.4$ poet --single pycodestyle
  resource "pycodestyle" do
    url "https://files.pythonhosted.org/packages/e1/88/0e2cbf412bd849ea6f1af1f97882add46a374f4ba1d2aea39353609150ad/pycodestyle-2.3.1.tar.gz"
    sha256 "682256a5b318149ca0d2a9185d365d8864a768a28db66a84a2ea946bcc426766"
  end
bash-4.4$
```
