### ISSUE TITLE
error with annotation only lines starting "for"

### ISSUE THREAD

**Issue by samuelcolvin** [PyCQA/pycodestyle#661]
```python
from typing import NamedTuple


class FooBar(NamedTuple):
    forx: str
```

```
➤  pycodestyle test.py 
flake_error.py:5:9: E701 multiple statements on one line (colon)
```

This doesn't happen if I renamed `forx` to not start `for...`.

**Comment by IanLee1521** [comment]
Thanks for catching this! Sounds like an issue with the regex, want to take a crack at updating it?

I suspect, though on my phone so can't confirm, that this is the correct regex to look at : `STARTSWITH_INDENT_STATEMENT_REGEX`

Please include the test case you posted above if you do take a crack at this. :)

**Comment by sigmavirus24** [comment]
Have you tested against master? I believe we have this fixed already.

**Comment by samuelcolvin** [comment]
seems to be fixed on master, sorry.
