### ISSUE TITLE
Is there a newline character style rule?

### ISSUE THREAD

**Issue by jian-wu** [PyCQA/pycodestyle#664]
Hi, my apologies if this has been asked before. But how do I add a linter rule for making sure all files use one newline character? Say, I only want all of my files in the repo to use \n instead of \r\n or \r. Please shed some light. Thanks.

**Comment by asottile** [comment]
pep8 (and therefore pycodestyle) don't have an opinion on this -- that said, if you're looking for something which checks this you could use [`mixed-line-ending`](https://github.com/pre-commit/pre-commit-hooks#mixed-line-ending) from `pre-commit-hooks` (it has both a fix and validate mode)
