### ISSUE TITLE
How to add a check to verify that all packages have a README.md file

### ISSUE THREAD

**Issue by mitar** [PyCQA/pycodestyle#668]
I would like to require that every sub-package (sub-directory with `__init__.py`) of my larger Python package contains a `README.md` file. It seems this is not really possible to do with current plugin system?

**Comment by sigmavirus24** [comment]
This would be better as a separate tool altogether. pycodestyle and friends (e.g., pydocstyle, flake8, mccabe, pyflakes, etc.) are all about checking the contents (style, validity, etc.) of python files, not the structure of directories or enforcing rules about what files exist and where.
