### ISSUE TITLE
E721 false positives

### ISSUE THREAD

**Issue by saleemrashid** [PyCQA/pycodestyle#671]
In https://github.com/trezor/python-trezor/pull/124, there are comparisons like `msg.type == types.PinMatrixRequestType_Current`, where `msg.type` and `types.PinMatrixRequestType_Current` are `int`.

 This gives a false positive because `COMPARE_TYPE_REGEX` does not check if `type` is a function call, and `PinMatrixRequestType_Current` contains the word `Type`.

**Comment by asottile** [comment]
while #830 is a duplicate of this one, I believe that one has more information so we can continue discussion there!
