### ISSUE TITLE
Documentation inconsistency for ignored messages?

### ISSUE THREAD

**Issue by ghazpar** [PyCQA/pycodestyle#685]
HI!

The documentation says that the following messages are ignored by default:

> checks E121, E123, E126, E133, E226, E241, E242, E704 and W503 are ignored

But the source code defines the following variable:
`DEFAULT_IGNORE = 'E121,E123,E126,E226,E24,E704,W503'
`
So which is which? Moreover, there is no error message E24 (see default variable).

At first, I was using the default parameters. Then I wanted to ignore an additional warning message, but realized that the default ignores are no longer ignored when you specify something to ignore. This unexpected behavior was surprising to me. I think it should be either corrected or better documented. 

Best regards.

**Comment by IanLee1521** [comment]
Hi @ghazpar -- 

The ignore of `E24` means all `E24x` checks, of which, `E241` and `E242` are the only ones.

That said, there does appear to be a discrepancy with `E133`. Let me look into that.

**Comment by sigmavirus24** [comment]
Regarding the behaviour of `--ignore`

>  I think it should be either corrected or better documented.

I thought it was clear that it was an *override* behaviour, not an *extension* behaviour in the documentation. That said, I'm on my phone so I can't verify if my memory is serving me well. Either way, that has been the behaviour for *years* and will not change.

**Comment by ghazpar** [comment]
Well I haven't seen anything explicit in the documentation about that. Moreover, at first I even didn't notice that some messages were ignored by default. Perhaps, you should add an explicit section about ignore and select options. In that section, you could make explicit the shortcuts for ignoring or selecting subsets of messages (it's a cool feature that can't be guessed).

Best.

**Comment by toshiki-h** [comment]
Hi!

I am Toshiki. I would like to start contributing to this project. May I take on this issue? 
What we need to do seems that we clearly explain in intro.rst that the default setting will be overridden when ignoring an additional warning. If my understanding is wrong, please correct me and give me some pieces of advice! Thank you for your time.

Best regards,

**Comment by toshiki-h** [comment]
Hi @IanLee1521 ,

Thank you for your reply.
Ok, I see. I will start a PR.

Best regards,
