### ISSUE TITLE
Brackets with return statement

### ISSUE THREAD

**Issue by sobolevn** [PyCQA/pycodestyle#687]
I have the following example:

```python
def return_value():
     return(10)
```

This working code is considered correct. Should it be this way? 

My toolchain:

> pycodestyle==2.3.1
> pyflakes==1.5.0 
> flake8==3.4.1

**Comment by IanLee1521** [comment]
I think so. In this case I think it's using `return` as a function, instead of a statement.

It's still syntactical valid in Python 3.6.2, so I think that yes, it should be.

**Comment by sobolevn** [comment]
I will write a plugin not to allow this kind of code. Thanks!

**Comment by FichteFoll** [comment]
Maybe a space could be required to occur after the return keyword?  I imagine it would work the same for others like yield, await, and del.

**Comment by sobolevn** [comment]
I have started a separate project for that: https://github.com/sobolevn/flake8-parenthesis

**Comment by anntzer** [comment]
Any chance for reopening this issue?  The argument that it's syntactically valid shouldn't be so relevant here (pycodestyle warns about many constructs that are syntactically valid, after all), and clearly, treating `return` as a "function" is just... wrong.

**Comment by sobolevn** [comment]
@anntzer since this issue is quite old, I want to post an update. I have started this project: https://github.com/wemake-services/wemake-python-styleguide

It has this rule and many-many others.
