### ISSUE TITLE
mutable default arguments

### ISSUE THREAD

**Issue by dvolgyes** [PyCQA/pycodestyle#698]
While it is not necessarily a bug, but most of the time it is a bad idea
to use mutable types (e.g. list, dict, set) as default values for arguments.
These are evaluated once,  and they keep their state.

This could be used for caching, etc., too, but more often it is a bug.
http://docs.python-guide.org/en/latest/writing/gotchas/

So it would be nice to create a warning for these kind of situations.

**Comment by sigmavirus24** [comment]
That is covered in https://github.com/PyCQA/flake8-bugbear#list-of-warnings which means pycodestyle will not add it.
