### ISSUE TITLE
Mnemonic prefixes break pycodestyle --diff execution

### ISSUE THREAD

**Issue by mic4ael** [PyCQA/pycodestyle#701]
In the `diff` section in my gitconfig I have an option `mnemonicprefix` set to `true`. This means that git will use `i/w/c/o` instead of `a/b/c/d` in the generated diff. Apparently that breaks execution of `pycodestyle` when `--diff` argument is provided.

Command:

    git diff -U0 --staged | pycodestyle --diff --max-line-length=120

Output:

    ./i/path.py:1:1: E902 IOError: [Errno 2] No such file or directory: './i/path.py'

To fix it I could use `--no-prefix` in git but I am wondering whether this should be handled by `pycodestyle` itself.

**Comment by IanLee1521** [comment]
Since you are using output from git as the input to pycodestyle, rather than an actual Python file, I'm inclined to say this is something that should *not* be handled here. If you feel differently and would like to make a pull request though, we would be able to review that for you.

**Comment by mic4ael** [comment]
Ok, you can have a look at my PR and let me know what you think.
