### ISSUE TITLE
Wrong or non-existent column number

### ISSUE THREAD

**Issue by lucasdf** [PyCQA/pycodestyle#704]
In some occasions, pycodestyle is returning the wrong or non-existent column number. We are facing some issues on [AtomLinter/linter-flake8](https://github.com/AtomLinter/linter-flake8) due to this problem. This issue happens when using extended characters.

A simple reproduction:
1. Create a file named foo.py and include the content below. Notice that there is a single whitespace after the special dot character.
```
• 
```
2. Execute `pycodestyle foo.py`. The output is `foo.py:1:4: W291 trailing whitespace`. The message references line 1 and column 4. There is no column 4 in the file.

This seems to be some encoding issue. It seems that the character `•` is being treated as multiple characters.

**Comment by Arcanemagus** [comment]
Any update on this? I semi-regularly get issues filed against `linter-flake8` that are caused by this at their root.

**Comment by sigmavirus24** [comment]
What version of Python is encountering this bug?

**Comment by Arcanemagus** [comment]
Ones that have been linked here:
* `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.0 on Windows`
* `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1 on Windows`
* `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.5.0 on Windows`
* `2.5.5 (pep8: 1.5.7, pyflakes: 0.8.1, hacking.core: 0.0.1, ProxyChecker: 0.0.1, mccabe: 0.2.1) CPython 3.5.2 on Windows`

It seems there have been a few different issues that trigger that error message so it's hard to track down what versions exactly are affected (that last one _might_ be a different issue).

**Comment by asottile** [comment]
I can't reproduce the findings:

```console
$ pycodestyle t.py
t.py:1:2: W291 trailing whitespace
$ pycodestyle --version
2.5.0
```
