### ISSUE TITLE
Drop support for EOL Python versions?

### ISSUE THREAD

**Issue by hugovk** [PyCQA/pycodestyle#715]
I'd like to suggest pycodestyle only supports non-EOL Python versions.

Python 2.6, 3.2 and 3.3 are EOL and no longer receive security updates.

![image](https://user-images.githubusercontent.com/1324225/33826009-275286e4-de6c-11e7-8f70-781433006423.png)

Here's the pip installs for pycodestyle from PyPI for the last month (via `pypinfo --percent --pip --markdown pycodestyle pyversion`) showing low numbers for the EOL versions.

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   49.2% |        475,779 |
| 3.6            |   23.7% |        229,441 |
| 3.5            |   18.9% |        182,682 |
| 3.4            |    6.8% |         66,030 |
| 3.3            |    0.6% |          5,971 |
| 3.7            |    0.4% |          3,927 |
| 2.6            |    0.4% |          3,777 |
| 3.2            |    0.0% |            317 |

https://github.com/PyCQA/pycodestyle/blob/master/docs/developer.rst#direction says:

> * Python 2.6 support is still deemed important.

This was added two years ago (https://github.com/PyCQA/pycodestyle/pull/460), is this still the case?

Some other PyCQA projects are planning on ending all Python 2 support around mid-2018 when Python 3.7 is due out (https://github.com/PyCQA/meta/issues/19).

**Comment by sigmavirus24** [comment]
@hugovk please stop spamming PyCQA projects with this specific information. @IanLee1521 and I have both weighed in on the issue you mention. The fact that you're sending this to every project indicates an attempt to start arguments with the organization and projects over their independent leadership. Please address the specific project owners in the issue you keep linking. If they've already responded, you can assume that the project is going to drop support when it has the time and inclination.

**Comment by hugovk** [comment]
Apologies, the meta issue is about 2.x and dropping 2.7 before it is EOL in 2020. 

This is about 2.x and 3.x versions which are already EOL. 

I had checked the meta issue and these two projects aren't specifically mentioned there, nor do I see anything from Ian. 

No arguments are sought, I thought these decisions are up to each individual project but I'm not familiar with how things are organised and don't wish to cause problems. 

As requested, in the future I'll address people from meta. Sorry again.
