### ISSUE TITLE
Incorrect E701 if annotated variable name begins with class or def

### ISSUE THREAD

**Issue by euresti** [PyCQA/pycodestyle#716]
Using python 3.6 with variable annotations (https://www.python.org/dev/peps/pep-0526/) runs into interesting errors depending on the name of the variable.

```
class Foo:
    classification: int
    definition: int
    _def: int
    _class: int


def foo():
    class_foo: int
    def_value: int
```

t4.py:2:19: E701 multiple statements on one line (colon)
t4.py:3:5: E704 multiple statements on one line (def)
t4.py:9:14: E701 multiple statements on one line (colon)
t4.py:10:5: E704 multiple statements on one line (def)

I'm not sure if other keywords are affected.

**Comment by euresti** [comment]
Never mind it's this #682

**Comment by brianbruggeman** [comment]
I'm not sure if this is the same issue...

#682 references only E701.

You have errors for E704 as well up there.
