### ISSUE TITLE
Add style checker rule to make sure we have the blank line before starting doctests.

### ISSUE THREAD

**Issue by rekhajoshm** [PyCQA/pycodestyle#723]
Add style checker test to make sure we have the blank line before starting doctests.

**Comment by FichteFoll** [comment]
This is a task for [pydocstyle](http://www.pydocstyle.org/en/2.1.1/error_codes.html).

**Comment by sigmavirus24** [comment]
I agree with @FichteFoll so I'm going to close this out.
