### ISSUE TITLE
Version on pypi is a year old.

### ISSUE THREAD

**Issue by euresti** [PyCQA/pycodestyle#725]
Happy birthday to pycodestyle 2.3.1!
Can a new version be released?  There are lots of bug-fixes that I'm sure the world would appreciate!

**Comment by FichteFoll** [comment]
And new features like W504.

**Comment by IanLee1521** [comment]
Yeesh... Yes, I should get on that...

**Comment by JakobGM** [comment]
Gentle reminder, @IanLee1521 :) 

Waiting #710 to be implemented :tada:

**Comment by hoylemd** [comment]
@JakobGM #710 looks like it's done to me.  Did you mean to link to a different issue or am I missing something?

**Comment by sigmavirus24** [comment]
I've had various people volunteer to write changelogs to make it easier to cut a release. If anyone wants to through together something for the release I could potentially do this tonight or tomorrow night.

**Comment by hugovk** [comment]
Here's a list of what's been merged since the last release: https://github.com/PyCQA/pycodestyle/compare/1.7.1...master

**Comment by sigmavirus24** [comment]
@hugovk that is neither accurate nor what I asked for

**Comment by hugovk** [comment]
I updated the link, it's to help someone write a changelog.

**Comment by IanLee1521** [comment]
Thanks @JakobGM that would be great. You are correct, it is not yet been released to PyPI.

For the changelog, you can use what @hugovk left as a list of the diff (https://github.com/PyCQA/pycodestyle/compare/2.3.1...master) as a reference, but you'll probably need to compare that against the actual merged pull requests to combine the two.

The changelog is at https://github.com/PyCQA/pycodestyle/blob/master/CHANGES.txt, and you can see there is already a bit of work to fill in the changes, but we need to complete it.

Thank you!

**Comment by JakobGM** [comment]
Ok, then I understand :stuck_out_tongue:

**Comment by JakobGM** [comment]
Okay, I have now read the git log and included any relevant items in ``CHANGES.txt`` as a part of #740.

I will update the pull request if you think something is missing, or if I have included anything irrelevant :smile:

**Comment by sigmavirus24** [comment]
2.4.0 i son PyPI! :tada: Thank you @JakobGM for helping get this out the door. :+1:
