### ISSUE TITLE
Wrong behaviour with W601 and W503

### ISSUE THREAD

**Issue by mastak** [PyCQA/pycodestyle#726]
Step to reproduce:
1. Create code with `W503`:
```
def update_actions():
    return (
        some_big_function_name_1()
        + some_big_function_name_2()
    )
``` 
 \> `some.py`
2. `pycodestyle ./some.py` => empty output
3. Add `pycodestyle` settings 
```
[pycodestyle]
ignore = W601
``` 
\> tox.ini
4. `pycodestyle ./some.py` =>
`./some.py:4:9: W503 line break before binary operator`

With default settings, there is no warning, but if you add a rule to ignore `W601` pycodestyle shows `W503` errors.

**Comment by FichteFoll** [comment]
W503 is ignored by default, as are [some others](https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes). When you set `ignore` directly, the default ignores get overridden.
