### ISSUE TITLE
URL in comments not ignored when max_line_length below 10

### ISSUE THREAD

**Issue by saksham189** [PyCQA/pycodestyle#744]
### Steps to Reproduce

1. Write a python file with a comment with a long url i.e. 
`# https://github.com/PyCQA/pycodestyle/issues/new`
2. Now run `pycodestyle filename.py --max-line-length=8`

### Current behavior
Error E501 `E501 line too long (57 > 9 characters)`

### Expected behavior
No errors

Indeed this happens for any value of max-line-length below 10. Is there any minimum on the max-line-length value?

**Comment by anctartica** [comment]
Looks like this happens due to this patch:
https://github.com/PyCQA/pycodestyle/commit/fed43c5b560c90995e2ea3f742f2bf6b6e497657#diff-429d64b260de27fe3688921a1592b3f6R225
The contributor has subtracted 7 from the max_line_length. Why is this needed? In any case I would be interested in contributing.

**Comment by sigmavirus24** [comment]
I don't know why `7` is a magic number there. I do understand that they were trying to guard against something like:

```
# --max-line-length=5
#     https://some-really-long-url.com/path/to/some/useful/information
```

Note the leading spaces exceed the max line length.

That said, I'd be interested in hearing your use-case for a `--max-line-length` less than 10 (really less than 72). Without understanding that, this seems like a contrived edge case that may be better to acknowledge than attempt to fix.

**Comment by anctartica** [comment]
Yes, I must admit that `--max-line-length` less than 10 is stupid for python code being linted, therefore this can be safely ignored.

**Comment by sigmavirus24** [comment]
@anctartica that doesn't really answer my question though. What's your use-case for such a short line-length?

**Comment by anctartica** [comment]
I don't have a use case for this. I was looking through the code and could not understand this part. 
Anyways it is possible to add an option such as `ignore_regex`that would ignore lines for the E501 rule?  This is because trivial changes in the string contents necessitate the string being re-joined and re-broken, causing unnecessary diff churn

**Comment by sigmavirus24** [comment]
> Anyways it is possible to add an option such as ignore_regexthat would ignore lines for the E501 rule? This is because trivial changes in the string contents necessitate the string being re-joined and re-broken, causing unnecessary diff churn.

I'm not sure this issue is the right place to request that feature. That should be discussed separately from this.

**Comment by anctartica** [comment]
Should I create a new issue then?

**Comment by jayvdb** [comment]
The magic number `7` may come from PEP8 [max line length 79](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) minus the PEP8 "flowing long blocks of text" length of 72.

**Comment by sigmavirus24** [comment]
@anctartica yes, please create a new issue.

**Comment by asottile** [comment]
closing since this seems unlikely to affect actual use cases of `pycodestyle`
