### ISSUE TITLE
E252 Mistakenly triggered by typing.

### ISSUE THREAD

**Issue by fflorens** [PyCQA/pycodestyle#760]
In this code example, mixing default value with type hints triggers E252 while it should not.

`$> pycodestyle --show-source --show-pep8 foo.py`
```foo.py:1:21: E252 missing whitespace around parameter equals
def foo(params: dict=None):
                    ^
    Don't use spaces around the '=' sign in function arguments.

    Don't use spaces around the '=' sign when used to indicate a
    keyword argument or a default parameter value, except when using a type
    annotation.

    Okay: def complex(real, imag=0.0):
    Okay: return magic(r=real, i=imag)
    Okay: boolean(a == b)
    Okay: boolean(a != b)
    Okay: boolean(a <= b)
    Okay: boolean(a >= b)
    Okay: def foo(arg: int = 42):
    Okay: async def foo(arg: int = 42):

    E251: def complex(real, imag = 0.0):
    E251: return magic(r = real, i = imag)
    E252: def complex(real, image: float=0.0):```

**Comment by sigmavirus24** [comment]
Quoting what you said above:

```
    Don't use spaces around the '=' sign when used to indicate a
    keyword argument or a default parameter value, except when using a type
    annotation.
```

Or in short "Don't use spaces around the '=' sign ... except when using a type annotation". I believe that's a quote from PEP-0008.

**Comment by zed** [comment]
There should be spaces around = sign if the function parameter is annotated: "Don't use spaces around the = sign when used to indicate a keyword argument, or when used to indicate a default value for an unannotated function parameter." https://www.python.org/dev/peps/pep-0008/

**Comment by est** [comment]
I was using py3.6 and had this error, upgrading to 3.7+ or 3.9 fixed this.

**Comment by asottile** [comment]
@est it shouldn't have, you most likely upgraded the pycodestyle version instead
