### ISSUE TITLE
W606 is not ignored with "# noqa"

### ISSUE THREAD

**Issue by jwkvam** [PyCQA/pycodestyle#762]
This isn't a big deal for me, I can just disable this check globally. I'm using a library that has a module called `async` so I can't change that easily myself. I wanted to disable this check when I import that library. Then I can still verify that the rest of my code doesn't use these reserved keywords.

**Comment by jwkvam** [comment]
I see. Is that the more recommended tooling? I use pylint and pycodestyle now. Is pylint + flake8 more common? I wasn't sure if flake8 would be redundant if I'm using pylint. Thank you for any guidance or pointers.

**Comment by sigmavirus24** [comment]
Pycodestyle is opinionated about what it allows you to use noqa for. Meanwhile Flake8 isn’t and it allows you to use that for just a single error code
