### ISSUE TITLE
Simultaneous E127 & E122 violation

### ISSUE THREAD

**Issue by supposedly** [PyCQA/pycodestyle#765]
_**Python version** 3.6.5, **pycodestyle version** 2.4.0._

(I *think* this is distinct from the other E127-related issues, like #758.)

Run pycodestyle on the following snippet, noting the position of the plus symbol in each block:

```py
def hmm():
    at_least_one_extra_line_needs_to_be_here: None
    (
      'an expression'
      'chopped up'
      'into lines'
      ) \
      + 'another expression'


def hm():
    at_least_one_extra_line_needs_to_be_here: None
    (
      'an expression'
      'chopped up'
      'into lines'
      ) \
    + 'another expression'

```

Result:
```
~$ pycodestyle test.py
test.py:8:7: E127 continuation line over-indented for visual indent
test.py:18:5: E122 continuation line missing indentation or outdented
~$ 
```

I'd expect at least one of them to pass (because the errors contradict each other), and indeed the E127 on line 8 does not appear under the following conditions:

```py
def hmm():
    # no preceding line(s)
    (
      'an expression'
      'chopped up'
      'into lines'
      ) \
      + 'another expression'
```
```py
# no indentation
at_least_one_extra_line_needs_to_be_here: None
(
  'an expression'
  'chopped up'
  'into lines'
  ) \
  + 'another expression'

```

**Comment by sigmavirus24** [comment]
Please provide the version of pycodestyle you're using and the version of python.

**Comment by eltrhn** [comment]
Apologies!! pycodestyle version 2.4.0 on Python 3.6.5. Edited into main post as well.

**Comment by supposedly** [comment]
Closing in favor of #862 -- same issue but expressed more-concisely. (my mention of E122 is something of a red herring)
