### ISSUE TITLE
E714 miscategorizes chained 'is not'

### ISSUE THREAD

**Issue by supposedly** [PyCQA/pycodestyle#767]
Python 3.6.5, pycodestyle 2.4.0

Misinterprets the first `is not`'s `not` as part of a `not foo is ...` expression.

test.txt:
```py
foo is not bar is not baz
```
output:
```
test:1:8: E714 test for object identity should be 'is not'
```
(not that chained `is not`s would ever appear in real/good code, but still worth noting)

**Comment by goodmami** [comment]
Just came across this bug and I'm happy to see a fix is committed.

> not that chained `is not`s would ever appear in real/good code [...]

I won't dispute whether my code is "good", but I have a "real" example. I implemented a union operator for a graph class and in my tests I wanted to make sure that the union of two graphs returned a new object and not a mutation of either the LHS or RHS of the operation.

https://github.com/goodmami/penman/blob/40f534c32c5547bdb2b22b18863d4d4e01c3bba7/tests/test_graph.py#L46

Just providing this for context in case someone stumbles on this issue later.
