### ISSUE TITLE
W293: emitted for multi-line strings in pycodestyle2.3.1

### ISSUE THREAD

**Issue by sinancepel** [PyCQA/pycodestyle#770]
Looks like `W293` (trailing whitespace on empty line) is getting triggered for string literals. I'd imagine that this is undesired behavior since the space might have semantic meaning?

```
# a.py
a = """
  
"""
$ pycodestyle --version
2.4.0
$ pycodestyle a.py
a.py:2:1: W293 blank line contains whitespace
```

**Comment by fmigneault** [comment]
I'm seeing the same behaviour when using this notation: 

```python 
import inspect

def make_msg():
    msg = inspect.cleandoc("""
    Title
    
    this is the message.
    """)
    return msg

```

Patterns should also consider matching triple quotes within function calls.

using: `pycodestyle==2.7.0`

**Comment by asottile** [comment]
my 2c is that the lint is still correct -- having trailing whitespace (even semantic and inside a triple-quoted string) is undesirable because it is impossible for a human to know it is there.

I think this should be wontfix and you're free to use `# noqa: W293` on the end of triple-quoted-string to ignore it via flake8

**Comment by fmigneault** [comment]
@asottile  Valid point. I agree.

**Comment by asottile** [comment]
given that I'll close this 👍

**Comment by raffienficiaud** [comment]
Seeing this now, it would be good to see in the documentation where to put the `# noqa: W293` (tried many things unsuccessfully until I reached this ticket).
Thanks!

**Comment by sigmavirus24** [comment]
This project doesn't support that syntax

**Comment by raffienficiaud** [comment]
I misunderstood this part below and I stand corrected, thank you for the clarification.
```
(^) These checks can be disabled at the line level using the # noqa special comment. 
This possibility should be reserved for special cases.
```
