### ISSUE TITLE
pycodestyle handles an extra closing parenthesis very poorly

### ISSUE THREAD

**Issue by thanatos** [PyCQA/pycodestyle#771]
Take, for example, this Python:

```python
async def main():
    foobar = await asyncio.gather(
        bar, baz, qux,
    ))  # N.b., an extra ) is here, by mistake.

    core.init(warp)
    http_session = aiohttp.client.ClientSession()

    async def thunk(messages):
        await process_messages(
            messages,
            warp_core,
        )

    consumer = \
        consume_messages(client, warp, core, thunk)
```

`pycodestyle` will emit the following:

```
./pycodestyle-weird-error.py:6:5: E122 continuation line missing indentation or outdented
./pycodestyle-weird-error.py:7:5: E122 continuation line missing indentation or outdented
./pycodestyle-weird-error.py:7:17: E251 unexpected spaces around keyword / parameter equals
./pycodestyle-weird-error.py:7:19: E251 unexpected spaces around keyword / parameter equals
./pycodestyle-weird-error.py:9:5: E122 continuation line missing indentation or outdented
./pycodestyle-weird-error.py:11:13: E113 unexpected indentation
./pycodestyle-weird-error.py:13:9: E901 IndentationError: unindent does not match any outer indentation level
```

I initially started trying to tackle the `IndentationError`, since that seemed the most egregious of the lot, and would prevent the code from running at all, as opposed to a mere stylistic violation. It took me a considerable while to figure out `pycodestyle` had sent me on a wild goose chase.

The actual error here is that there is an extra `)`, which attempts to close a `(` that was never opened. As a layman, it seems like that error (a mismatched parenthesis) should be easy to catch, and certainly, the situation would be a _lot_ clearer to me as a user if `pycodestyle` could emit the singular error message
```
…:4:?: E??? unmatched / extra closing parenthesis
```

or something along those lines.

That one character (`)`) is the only actual violation in the example. Removing it causes the file to pass `pycodestyle` without error.

(Now, my understanding is that some parser algorithms actually make this sort of good error reporting rather hard to do. So, this might all be very non-trivial.)

**Comment by asottile** [comment]
pycodestyle doesn't check syntax validity -- you're probably best to use a tool like `pyflakes` / `flake8` (which includes `pycodestyle` + `pyflakes`) to find such errors.

when the source isn't syntactical python, the output of `pycodestyle` is relatively undefined
