### ISSUE TITLE
Extend command line options with the config file

### ISSUE THREAD

**Issue by maxnordlund** [PyCQA/pycodestyle#773]
Currently they are all overridden, but for some, like ignore and exclude, it makes more sense IMHO to append the command line option to the list in the config file.

What do you think?

https://github.com/PyCQA/pycodestyle/blob/85f8f5e3ac349c0746df9544997ea346f9901061/pycodestyle.py#L2515-L2516

**Comment by maxnordlund** [comment]
Yeah, another flag would be fine. Maybe one that changes how these flags work, `--merge-options`?

**Comment by sigmavirus24** [comment]
Right, and I'm confident there are already issues open for them, so I'm closing this as a duplicate

**Comment by maxnordlund** [comment]
Then could you link the issue so that me, and others in the future, find that issue?

**Comment by ana-yankova** [comment]
+1 It'll be great to have --extend-ignore and --extend-exclude options.
@sigmavirus24 I couldn't find issues open about this. Is it possible to revisit this one and reopen it or link it to existing issues as @maxnordlund suggested?
