### ISSUE TITLE
mssing variables in f-string have no useful position information

### ISSUE THREAD

**Issue by AvdN** [PyCQA/pycodestyle#774]
I got this error:

```
./develop.py:1:2: F821 undefined name 'initpy'
# coding: utf-8

```

because an f-string in a class method accessed the incorrect (global) variable name:

```
                print(f'no _package_data in {initpy}?')
```
This was actually line 695. to have that line displayed instead of the first line of the file.

**Comment by asottile** [comment]
`F821` is from pyflakes and not from pycodestyle
