### ISSUE TITLE
Future Warning on Python 3.7

### ISSUE THREAD

**Issue by ErikPartridge** [PyCQA/pycodestyle#780]
Running pycodestyle on the latest version of Python 3.7 is giving the following future warning:

``/usr/local/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
``

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.

https://github.com/PyCQA/pycodestyle/pull/735
https://github.com/PyCQA/pycodestyle/issues/728
