### ISSUE TITLE
Issues with pycodestyle version?

### ISSUE THREAD

**Issue by MikkelDK** [PyCQA/pycodestyle#783]
Hello.

I have some issues with installation of pycodestyle. where i do this:
pip install pycodestyle. and i getting this error/issue:

`flake8 3.5.0 has requirement pycodestyle<2.4.0,>=2.0.0, but you'll have pycodestyle 2.4.0 which is incompatible. `

How can i fix that? ;o

**Comment by NMuatan** [comment]
Hi. 

I can't reproduce the bug. Which system are you on? Is your pip and your system up to date?

**Comment by MikkelDK** [comment]
Hello, i'm on Debian 9.4. and both is updated yes.

**Comment by FichteFoll** [comment]
flake8 doesn't work with the latest pycodestyle yet, so you can only use either (i.e. use flake8 with a version <2.4 or use 2.4 but without flake8; or use flake8 from git). See https://github.com/PyCQA/pycodestyle/issues/741.
