### ISSUE TITLE
Checking for invalid escape sequences in docstrings yields negative column numbers

### ISSUE THREAD

**Issue by FichteFoll** [PyCQA/pycodestyle#795]
```
/tmp/test Δ cat test.py
def func():
    """this is a
    long-ish docstring
    with invalid \d escapes
    """
    pass

/tmp/test Λ pycodestyle test.py
test.py:5:-12: W605 invalid escape sequence '\d'
 ?=1
/tmp/test $ pycodestyle --version
2.4.0
```

**Comment by FichteFoll** [comment]
I suspect it's [this line](https://github.com/PyCQA/pycodestyle/blob/566cdc0cb22e5530902e456d0b315403ebab980c/pycodestyle.py#L1538). I have no idea how this can return anything less than `-1`, but this clearly wasn't designed for multi-line strings.

**Comment by sigmavirus24** [comment]
Worth keeping in mind that `logical_line` is different from `physical_line` for pycodestyle too and this check uses the `logical_line` that means that we consider that to all be one string on one line. I suspect using `physical_line` might present other challenges but would be worth trying to use. Unfortunately, I see no point in the future where I will have time to do that work

**Comment by asottile** [comment]
This is probably due to https://bugs.python.org/issue16806 (try the same in `pypy` where this is fixed)

**Comment by mgedmin** [comment]
-12, -7, bah!  I give you -3036:

```
./tests/test_safety.py:102:-3036: W605 invalid escape sequence '\_'
./tests/test_safety.py:102:-2770: W605 invalid escape sequence '\_'
./tests/test_safety.py:102:-2566: W605 invalid escape sequence '\_'
./tests/test_safety.py:102:-2548: W605 invalid escape sequence '\_'
./tests/test_safety.py:102:-2536: W605 invalid escape sequence '\_'
./tests/test_safety.py:102:-2528: W605 invalid escape sequence '\_'
./tests/test_safety.py:102:-2237: W605 invalid escape sequence '\_'
```

(flake8 on [this litle module](https://github.com/mgedmin/safety/blob/d39980d4a763fe0d6707879ce0a5b4d1f848889d/tests/test_safety.py).)

**Comment by mgedmin** [comment]
It is sort-of fixed:
```
./tests/test_safety.py:74:71: W605 invalid escape sequence '\_'
./tests/test_safety.py:74:71: W605 invalid escape sequence '\_'
./tests/test_safety.py:74:71: W605 invalid escape sequence '\_'
./tests/test_safety.py:74:71: W605 invalid escape sequence '\_'
./tests/test_safety.py:74:71: W605 invalid escape sequence '\_'
./tests/test_safety.py:74:71: W605 invalid escape sequence '\_'
./tests/test_safety.py:74:71: W605 invalid escape sequence '\_'
```

As you can see all the errors point to the same line and column, which is the first `"` of the opening `"""`, rather than the actual lines/columns where those `\_` show up.

**Comment by mgedmin** [comment]
(As penance for my information-less [comment](https://github.com/PyCQA/pycodestyle/issues/795#issuecomment-440796968) I will try to come up with a PR.  I originally didn't notice you had this fixed in #808, because this issue is still open -- apparently github doesn't understand the "resolves #nnn" syntax.)

**Comment by asottile** [comment]
ah, that position makes sense to me -- that's the token which has the problem.

an aside, if you want to automatically fix these I've added support to [`pyupgrade`](https://github.com/asottile/pyupgrade#invalid-escape-sequences) to autofix

**Comment by mgedmin** [comment]
I've made a PR as promised: #818.

**Comment by sigmavirus24** [comment]
And merged! I'll close this now
