### ISSUE TITLE
Multiple statements on one line bug

### ISSUE THREAD

**Issue by tehtekjess** [PyCQA/pycodestyle#804]
Experienced a bug in pycodestyle 2.3.1, have not tested in latest.

Test Case:
`from typing import NamedTuple

class SomeInfo(NamedTuple):
    internal_information_field: str
    foreign_information_field: str
    data: bytes

test = SomeInfo("test1", "test2", b"test3")
`
Gives an error "../test.py:12:24: E701 multiple statements on one line (colon)
I think it encounters the letter sequene "for" and it thinks it is a statement.
It was something I encountered on a project where we use pycodestyle, and I apologize for the brevity of my report.

**Comment by asottile** [comment]
This is fixed in 2.4.0:

```
$ ~/workspace/venvflake8/bin/pycodestyle t.py 
$ ~/workspace/venvflake8/bin/pycodestyle t.py --version
2.4.0
```
