### ISSUE TITLE
not showing error on unknow variable

### ISSUE THREAD

**Issue by alexislg2** [PyCQA/pycodestyle#805]
Hello,
my pycodestyle (v 2.4.0) is showing me errors for line-indents, line too long, etc... But does not show me any error about undefined variable.

For example consider this python file:
```
print(a)
```

I would expect to have an error since `a` is undefined when I run `pycodestyle test.py` but I have nothing

How can I debug this?

**Comment by sigmavirus24** [comment]
Are you mistaking pycodestyle for pyflakes?

**Comment by alexislg2** [comment]
whoops. Thanks ;)
