### ISSUE TITLE
Option to inherit default ignore list

### ISSUE THREAD

**Issue by bdarnell** [PyCQA/pycodestyle#816]
The most recent release of pycodestyle introduced a new warning, W504. This warning was disabled by default, so it was not disruptive to project using the default configuration. But as soon as a project ignores some warnings, this ignore list is used instead of the default, so these projects are disrupted by the addition of the new warning (tornadoweb/tornado#2526). I would like to be able to inherit the default ignore list so that I don't have to duplicate parts of it in my application's config and pycodestyle can continue to add warnings that are disabled by default without immediately affecting my projects.

(Yes, I should be pinning a particular version of the tool instead of just pulling the latest in my CI scripts)

**Comment by sigmavirus24** [comment]
Flake8 provides this functionality and we prefer to have basic functionality for this tooling. If you want that more advanced functionality, Flake8 is the place to find it.
