### ISSUE TITLE
No complaint about imports,module dunders defined above module docstring

### ISSUE THREAD

**Issue by Tadaboody** [PyCQA/pycodestyle#824]
It is mentioned in [pep8](https://www.python.org/dev/peps/pep-0008/#module-level-dunder-names) that

> module level "dunders" (i.e. names with two leading and two trailing underscores) such as __all__, __author__, __version__, etc. should be placed after the module docstring but before any import statements except from __future__ imports. Python mandates that future-imports must appear in the module before any other code except docstrings:

Although not specified explicitly, imports should be after the module docstring.
This is also necessary for them to be written in the modules `__doc__`

**Comment by Tadaboody** [comment]
I don't know if it's technically a pep8 issue but autopep8 which relies on this library fails on this https://github.com/hhatto/autopep8/issues/459
There exists issue #615 talking about the module dunders, this is about module-level imports

**Comment by sigmavirus24** [comment]
So I think autopep8 is broken and trying to auto-fix E402 for you. That should detect `a = 42` above your imports as being a violation. I don't believe it's a problem with this project though. Happy to re-open if that turns out to be wrong, though.
