### ISSUE TITLE
make DOCSTRING_REGEX more appropriate

### ISSUE THREAD

**Issue by Hanaasagi** [PyCQA/pycodestyle#827]
I wanna use the `pycodestyle` api the check the code, and i found the `DOCSTRING_REGEX`. But it will match normal string.

```Python
DOCSTRING_REGEX = re.compile(r'u?r?["\']')
```

As mentioned in [PEP 257 -- Docstring Conventions](https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring)

> For consistency, always use """triple double quotes""" around docstrings. Use r"""raw triple double quotes""" if you use any backslashes in your docstrings. For Unicode docstrings, use u"""Unicode triple-quoted strings""".

I think 

```Python
DOCSTRING_REGEX = re.compile(r'u?r?["\']{3}')
```

will be better.

**Comment by asottile** [comment]
docstrings don't have to be triple quoted strings

```
$ cat t.py 
'I am a valid docstring'

print(__doc__)

$ python t.py 
I am a valid docstring
```

**Comment by Hanaasagi** [comment]
I misunderstood it.
