### ISSUE TITLE
Giving only a single error to ignore in setup.cfg does not work

### ISSUE THREAD

**Issue by MaxNoe** [PyCQA/pycodestyle#841]
e.g.
This does not work:
```
[pycodestyle]
ignore = E722   # ignore "do not use bare except"
```

This does:
```
[pycodestyle]
ignore = E722,   # ignore "do not use bare except"
```

**Comment by martemyev** [comment]
I think it will also work without the comma if you remove the comment (or put it on a separate line)

[pycodestyle]
# ignore "do not use bare except"
ignore = E722

**Comment by MaxNoe** [comment]
Yes it does!

So maybe, in the code, the comment shoudl be striped away fist

**Comment by sigmavirus24** [comment]
Flake8 handles this, and it's handled for free on Python 3. pycodestyle isn't quite under highly active development and trying to do this ourselves would introduce yet more needless duplication between us and Flake8 and further maintenance burden that we can not sustain.

**Comment by MaxNoe** [comment]
I am on python 3

**Comment by sigmavirus24** [comment]
Because the tool works on 2 and 3 we may not be supplying everything we can to take advantage of py3

**Comment by MaxNoe** [comment]
Ah, it sounded like this shouldn't have occured when running on python 3, sorry.

**Comment by sigmavirus24** [comment]
I can see how my comment could be read that way. Sorry about that. I'll try to be clearer in the future.
