### ISSUE TITLE
Prevent E123 for function definitions

### ISSUE THREAD

**Issue by antonagestam** [PyCQA/pycodestyle#842]
Is there a way to prevent E123 for function definitions? The reason is I would like to be able to use the following style below for function definitions.

```python
def measure(
        request: HttpRequest,
        plan_id: Optional[int] = None,
        hole_id: Optional[int] = None,
        ) -> HttpResponse:
    hole = get_hole(plan_id, hole_id)
    ...
```

**Comment by asottile** [comment]
E123 is disabled by default (for this reason) (so I don't think this issue is valid?)

That said, I'd write this:

```python

def measure(
        request: HttpRequest,
        plan_id: Optional[int] = None,
        hole_id: Optional[int] = None,
) -> HttpResponse:
    hole = get_hole(plan_id, hole_id)
    ...

**Comment by sigmavirus24** [comment]
I whole-heartedly agree with @asottile on this one. It's disabled by default, so if you're overriding `ignore` (which seems like the most probable cause) you can safely and (hopefully uncontroversially) add it back to `ignore`.

**Comment by antonagestam** [comment]
Oh, the real issue here was I didn't realize `ignore` overrides the default. Is there no option to append to a list of default ignored values? That seems like a more intuitive and friendly behavior to me, instead of having to maintain a list of updated default values?

**Comment by asottile** [comment]
`flake8` has `--extend-ignore` fwiw
