### ISSUE TITLE
E502: false positive.

### ISSUE THREAD

**Issue by pvinci** [PyCQA/pycodestyle#844]
The following valid code triggers E502.

            raise subprocess.CalledProcessError(
                "Command {0} failed with return code: {1}.{2}" \
                "Process error output: {2}{3}" \
                .format(command, self.process.returncode, os.linesep, err))

**Comment by asottile** [comment]
The tool is correct, those backslashes do nothing

**Comment by pvinci** [comment]
You are correct.  Thanks for such a quick response!
