### ISSUE TITLE
Argument name <arg> doesn't conform to snake_case naming style

### ISSUE THREAD

**Issue by poreklo** [PyCQA/pycodestyle#855]
With pep8 1.7.1.

![mstsc_2019-03-18_17-37-35](https://user-images.githubusercontent.com/24385191/54530427-8c5ed480-49a4-11e9-8f2b-3190d66853b3.png)

warning about no snake_case naming style

![mstsc_2019-03-18_17-38-27](https://user-images.githubusercontent.com/24385191/54530460-a698b280-49a4-11e9-8948-8675d3a42aee.png)

which is a bit strange.

**Comment by sigmavirus24** [comment]
Is it safe to assume that you closed this because you realized that this is coming from `pylint`?

**Comment by poreklo** [comment]
yes, you understood me correctly
