### ISSUE TITLE
E302 expected 2 blank lines, found 0 for single multiline function definition in file

### ISSUE THREAD

**Issue by tbicr** [PyCQA/pycodestyle#860]
python: 3.7.2
pycodestyle: 2.5.0

E302 expected 2 blank lines, found 0 for single multiline function definition in file, but no issue single line function definition

haven file:

```
def test(
    param_1234567890_1, param_1234567890_2, param_1234567890_3, param_1234567890_4
):
    pass
```

run:
`flake8 file.py`

got:
`file.py:1:1: E302 expected 2 blank lines, found 0`

expected:
no issue as for file with next content:
```
def test(param_1234567890_1, param_1234567890_2, param_1234567890_3, param_1234567890_4):
    pass
```

**Comment by asottile** [comment]
Duplicate of #473
