### ISSUE TITLE
2.5.1 release

### ISSUE THREAD

**Issue by therefromhere** [PyCQA/pycodestyle#861]
Can we get a 2.5.1 release?

Thanks!

**Comment by GPHemsley** [comment]
PRs that would be included in a 2.5.1 release:
* #832
* #837
* #848
* #847
* #850
* #853
* #859
* #875

**Comment by asottile** [comment]
given some of those would trigger new lint errors I think the next release should be 2.6.0?

**Comment by FichteFoll** [comment]
There are also a couple open PRs that are required for Python 3.8 compatibility.

**Comment by asottile** [comment]
from flake8's perspective I'd also like to see #880 resolved before the next release

**Comment by asottile** [comment]
tracking the next release in #911
