### ISSUE TITLE
E302 force 2 spaces at the start of the file

### ISSUE THREAD

**Issue by Pycz** [PyCQA/pycodestyle#884]
Hello. I meet an issue today. 
`pycodestyle` on this code:

```python
def test(
    param
):
    print(param)

```
 says 
```
$ pycodestyle test.py
test.py:1:1: E302 expected 2 blank lines, found 0
```
but this version works fine:
```python
def test(param):
    print(param)

```
Is this a bug or intended behaviour?
Pycodestyle version - 2.5.0, ubuntu 16.04, python 3.7.3

**Comment by asottile** [comment]
it's a bug, #860 is a duplicate

**Comment by Pycz** [comment]
Got it

**Comment by asottile** [comment]
no problem! thanks for the issue :tada:
