### ISSUE TITLE
E501: Generalize #224 to accomodate reST in docstrings

### ISSUE THREAD

**Issue by zackw** [PyCQA/pycodestyle#888]
Consider this docstring:

```python
class DateTimeFormatter(object):
    """Convenience object that exposes static methods to convert a date, time or
    datetime object to a string representation suitable for various metadata
    standards.

    This is needed because python’s
    `strftime() <http://docs.python.org/library/datetime.html#strftime-strptime-behavior>`_
    doesn’t work for years before 1900.
    """
```

The line with the URL gets dinged for an E501 violation.  The exception for unbreakable single tokens (#224) does not apply because the URL _would_ fit into 80 columns if I put a line break right before the `<`.  But I'm pretty sure that if I do that, docutils will not recognize the link anymore.

**Comment by flying-sheep** [comment]
Also of course the more elegant link syntax:

```restructuredtext
This is needed because python’s `strftime()`_ doesn’t work for years before 1900.

.. _strftime(): https://docs.python.org/library/datetime.html#strftime-strptime-behavior

**Comment by sigmavirus24** [comment]
> Also of course the more elegant link syntax:
> 
> ```
> This is needed because python’s `strftime()`_ doesn’t work for years before 1900.
> 
> .. _strftime(): https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior
> ```

```
.. _strftime():
    https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior
```

Also works with reStructuredText and passes E501:

```
~ ❯ bat t.py && pycodestyle --select E501 t.py && echo "Exit: $?"
───────┬─────────────────────────────────────────────────────────────
       │ File: t.py
───────┼─────────────────────────────────────────────────────────────
   1   │ def foo():
   2   │     """Frobulate the timulator.
   3   │
   4   │     This is needed because python’s `strftime()`_ doesn’t wo
       │ rk for years
   5   │     before 1900.
   6   │
   7   │     .. _strftime():
   8   │         https://docs.python.org/3/library/datetime.html#strf
       │ time-strptime-behavior
   9   │     """
  10   │     pass
───────┴─────────────────────────────────────────────────────────────
Exit: 0
~ ❯                                                      at 07:06:04
```

As it stands, I don't feel the feature-request is something that's maintainably something we can implement, so I'm going to close this

**Comment by flying-sheep** [comment]
It doen’t work if the URL is so long that it doesn’t even fit a full line.

**Comment by asottile** [comment]
@flying-sheep it does, pycodestyle has an exclusion for a line which is just a url on its own:

```console
$ pycodestyle --max-line-length 20 t.py
$ echo $?
0
```
