### ISSUE TITLE
E231 for trailing comma in list

### ISSUE THREAD

**Issue by remarkov** [PyCQA/pycodestyle#891]
I'm using Black to format the code but I also have checks in PyCharm that highlight the pep8 errors. So I noticed a conflict between the two which disturbs me. For some reason I could not find anything related to this in the issues of pycodestyle nor in the issues of Black. Here is the example that I have (and I doubt this is something unique):
```
> pycodestyle --show-source --show-pep8 settings.py                                                                              Tue Nov 12 12:42:20 2019
settings.py:11:70: E231 missing whitespace after ','
    "ALLOWED_HOSTS", cast=CommaSeparatedStrings, default=["127.0.0.1",],
                                                                     ^
    Each comma, semicolon or colon should be followed by whitespace.

    Okay: [a, b]
    Okay: (3,)
    Okay: a[1:4]
    Okay: a[:4]
    Okay: a[1:]
    Okay: a[1:4:2]
    E231: ['a','b']
    E231: foo(bar,baz)
    E231: [{'a':'b'}]
```

Even in the given example there is a similar syntax on line 2 which is okay by pep8 so why pycodestyle treats this as an error?

The full part of the code is this:
```
ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS", cast=CommaSeparatedStrings, default=["127.0.0.1",],
)
```

Thanks!

**Comment by asottile** [comment]
well for one: inline lists you don't need a comma

this tool also doesn't intend to implement black's interpretation of pep8 so you're going to find differences

the example in the OK is for tuples which are different from lists

**Comment by remarkov** [comment]
it seems I was too tired to think clearly when I posted this issue so please excuse me for that. after thinking again I totally understand that it does not make any sense to have a comma in the inline list. I have a habit to keep a trailing comma in multiline lists for will known reasons but I'm having hard time to understand why I thought the trailing comma should exist in the given example.
my reference to Black was just to show that the code was already formatted with another tool but of course my assumption that both tools has to produce the same result was incorrect.
I am closing this issue as irrelevant but I will not delete it just in case someone else will have that "problem" too.

@asottile thanks for your time!
