### ISSUE TITLE
Support PEP 572

### ISSUE THREAD

**Issue by matthewgdv** [PyCQA/pycodestyle#893]
Currently the walrus operator (assignment expressions), are not understood correctly by pycodestyle, generating incorrect errors on account of thinking that the colon is signifying scope, and that the whitespace rules around it should be those of a scope-denoting colon.

Below is a simple example:

![pycodestyle](https://user-images.githubusercontent.com/37582022/68942105-89202080-079f-11ea-9f7a-dd4f56e9fa06.png)

**Comment by asottile** [comment]
dupe of #865 (already fixed)

**Comment by matthewgdv** [comment]
I could've sworn I searched for it before posting. Maybe I just looked for "walrus" and "assignment". Anyway, I'll close this, sorry for the spam.
