### ISSUE TITLE
Inconsistent E127 in generator expression used as argument

### ISSUE THREAD

**Issue by anntzer** [PyCQA/pycodestyle#904]
As of pycodestyle 2.5.0
```
(x for x in container
 if somecond(x)
    and othercond(x))
```
generates no warning (which I think is correct) whereas
```
sorted(x for x in container
       if somecond(x)
          and othercond(x))
```
results in an (IMO incorrect) "E127 continuation line over-indented for visual indent".

**Comment by asottile** [comment]
(I can't edit since I'm not part of the project) -- could you fix the title to reference E131 instead of E127?

this is also a duplicate of #680 which (lol) you reported :)

**Comment by anntzer** [comment]
lol, I searched for E131 and didn't find anything, even though I had a very clear feeling that I had already seen this before, sorry for the noise :p
