### ISSUE TITLE
Offer to take up more maintainership here

### ISSUE THREAD

**Issue by asottile** [PyCQA/pycodestyle#909]
👋 

I'd like to contribute more here, and become a maintainer!

- I already keep a close eye on this repository (for `flake8`'s sake)
- I'm comfortable with projects of similar size
- I can (probably) help increase the release cadence (and would be wiling to take up work to make pre-releases / etc. a thing)

**Comment by asottile** [comment]
whew, ok I trimmed the backlog a bit and consolidated a bunch of duplicates

**Comment by hoylemd** [comment]
Thank you! You're alright :)
