### ISSUE TITLE
The Next Release (pycodestyle 2.6.x)

### ISSUE THREAD

**Issue by asottile** [PyCQA/pycodestyle#911]
:wave: I'm planning to organize the next release of pycodestyle

I'll be pinning this issue and collecting feedback on things that should end up in this release

Due to the number of contributions that have gone into `pycodestyle` since the last release, I'm planning to do this as `2.6.0a1` first (an alpha pre-release) -- this should hopefully expand the number of people trying the release (though I suspect not all that many will use the alpha still)

___

How you can help:

- try out the latest master on your repositories: `pip install --force-reinstall git+https://github.com/pypa/pycodestyle`
- review [open PRs](https://github.com/PyCQA/pycodestyle/pulls)

**Comment by asottile** [comment]
I believe #867 should be resolved before making this release so we have proper python3.8 support

**Comment by FichteFoll** [comment]
FWIW, I started running `master` on my code a couple weeks ago (on Python 3.8 codebases) and haven't encountered any issues so far.

**Comment by max-wittig** [comment]
Using c9708a18a17fbf17e0d88c1d1675ac1a926c4565 since a while in production

**Comment by aviramha** [comment]
Running on master (Python 3.8 codebase) for the last 2 months. Everything looks good. Waiting for PyPI release :)

**Comment by asottile** [comment]
I've published a changelog for 2.6.0a1 here: #922 -- I don't have permission to release to pypi so one of the project managers will have to do that if everything looks good 👍

**Comment by IanLee1521** [comment]
Published to https://pypi.org/project/pycodestyle/2.6.0a1/ sorry for the delay, @ me next time, since I have too much email filtering right now... :)

**Comment by asottile** [comment]
no problem! thanks @IanLee1521!

**Comment by stianjensen** [comment]
Since I only use this project as a subdependency of flake8, and flake8 has a <2.6.0 requirement - can I install the alpha version to help test it before a stable release somehow? I'm getting a version conflict if I just try to add a 2.6.0a1 dependency on pycodestyle in addition to my flake8 dependency.

**Comment by asottile** [comment]
@stianjensen you're too quick -- just wait a bit I'm working on it :P https://gitlab.com/pycqa/flake8/-/merge_requests/418

**Comment by IanLee1521** [comment]
@stianjensen - If you manually upgrade pycodestyle after installing flake8, pip will complain, but will install (though I can't vouch for it working beyond that):

```
$> pip list
Package     Version
----------- -------
entrypoints 0.3
flake8      3.7.9
mccabe      0.6.1
pip         20.0.2
pycodestyle 2.5.0
pyflakes    2.1.1
setuptools  46.1.3
wheel       0.34.2

$> pip install -U --pre pycodestyle
Collecting pycodestyle
  Using cached pycodestyle-2.6.0a1-py2.py3-none-any.whl (41 kB)
ERROR: flake8 3.7.9 has requirement pycodestyle<2.6.0,>=2.5.0, but you'll have pycodestyle 2.6.0a1 which is incompatible.
Installing collected packages: pycodestyle
  Attempting uninstall: pycodestyle
    Found existing installation: pycodestyle 2.5.0
    Uninstalling pycodestyle-2.5.0:
      Successfully uninstalled pycodestyle-2.5.0
Successfully installed pycodestyle-2.6.0a1

$> pip list
Package     Version
----------- -------
entrypoints 0.3
flake8      3.7.9
mccabe      0.6.1
pip         20.0.2
pycodestyle 2.6.0a1
pyflakes    2.1.1
setuptools  46.1.3
wheel       0.34.2
```

**Comment by sigmavirus24** [comment]
> though I can't vouch for it working beyond that

No one can, that's why there are those dependency bound :smile:

**Comment by asottile** [comment]
flake8 3.8.0a2 is out (well, it has been out for a few days, forgot to comment here) so I've been trying out the new pycodestyle -- the only regression I've found so far in my code (~78kloc) is #908 (I've put up a patch for that in #927)

**Comment by stianjensen** [comment]
Tested on my django+mypy codebase (also around 80kloc). The new walrus operator is working as expected, and the only new warning I get is `E741 ambiguous variable name 'l'` which I see is expected from the release notes :tada:

**Comment by asottile** [comment]
things have been quiet :) -- beyond #927 I think we're ready to remove the `a1` and release 2.6.0 -- would appreciate some reviews on that PR though in the meantime!

**Comment by sigmavirus24** [comment]
Should we sneak #931 in there too?

**Comment by asottile** [comment]
yes I think so 👍

**Comment by sigmavirus24** [comment]
Done on both accounts

**Comment by asottile** [comment]
sweet, I'll put together a changelog and then we can get this out!

**Comment by asottile** [comment]
#933 for that

**Comment by asottile** [comment]
oops, hasn't been released yet -- will resolve this when that happens (just merged the changelog for it!)

**Comment by IanLee1521** [comment]
Working on it now... :)

**Comment by IanLee1521** [comment]
And we are live! https://pypi.org/project/pycodestyle/2.6.0/

Huge shout out to @asottile for all the work on getting this done! All of the credit goes to them!
