### ISSUE TITLE
2.6.0a1 crash

### ISSUE THREAD

**Issue by Richardk2n** [PyCQA/pycodestyle#926]
This (admitedly somewhat convoluted) code `self.totalTaskExecutionTime += (taskExecutionTime := time()-t1)` produces some kind of error.

**Comment by asottile** [comment]
I cannot reproduce, please include the actual file and the output when running:

```console
$ python3.8 -m pycodestyle ../t.py
$ cat ../t.py 
self.totalTaskExecutionTime += (taskExecutionTime := time()-t1)
```

**Comment by Richardk2n** [comment]
I am sorry. As this happened directly after updating pycodestyle to an alpha i kind of jumped to the conclusion, that it is the culprit. This was wrong.

**Comment by asottile** [comment]
what happened?

**Comment by Richardk2n** [comment]
Apperently the version of pyflakes, that i had installed did crash. (It was a bit outdated). This caused all the linting in my IDE not to happen. It just happened, that the first code i decided to write with my new pycodestyle install was something that crashed pyflakes.

**Comment by FichteFoll** [comment]
pyflakes also required an update for the new 3.8 assignment operator syntax. It is likely you were running into that.
