### ISSUE TITLE
Add support for class attribute checking [google]

### ISSUE THREAD

**Issue by jtpavlock** [PyCQA/pycodestyle#955]
This is a feature request to add a check for class level attribute documentation.

As described in the [google style guide](https://google.github.io/styleguide/pyguide.html#384-classes):

> If your class has public attributes, they should be documented here in an Attributes section and follow the same formatting as a function’s Args section.

```python
class SampleClass:
    """Summary of class here.

    Longer class information....
    Longer class information....

    Attributes:
        likes_spam: A boolean indicating if we like SPAM or not.
        eggs: An integer count of the eggs we have laid.
    """

    def __init__(self, likes_spam=False):
        """Inits SampleClass with blah."""
        self.likes_spam = likes_spam
        self.eggs = 0

    def public_method(self):
        """Performs operation blah."""
```

**Comment by asottile** [comment]
this doesn't really fit with pycodestyle (which is mostly about whitespace issues) -- perhaps [`pydocstyle`](https://github.com/pycqa/pydocstyle) is a better place?

**Comment by jtpavlock** [comment]
Wow, I totally meant to post this there. Sorry! It's been a long day...

**Comment by sigmavirus24** [comment]
I swear, Guido threatening his lawsuit over using `pep*` names has confused me endlessly with the new package names
