### ISSUE TITLE
W605: could be a false positive on SQL Query?

### ISSUE THREAD

**Issue by a-wakeel** [PyCQA/pycodestyle#958]
Hi, 
I am getting this warning on a very complicated nested SQL Query:
**W605 invalid escape sequence '\\|'**

Could that be a false positive? Should it not only look at python source?
Previously it was fine, it emerged as i upgraded to the latest version of **pycodestyle** and **flake8**.

**Comment by asottile** [comment]
not a false positive, you'll need to make sure you make that a valid escape sequence before it becomes a syntax error in a future version of python (originally planned for 3.10 but it might move back to 3.11 iirc)

getting new lint errors when you upgrade linters should be expected, we add functionality in new versions to catch more mistakes :)

an easy way is to use the [pyupgrade](https://github.com/asottile/pyupgrade) code formatter which will [autofix this for you](https://github.com/asottile/pyupgrade#invalid-escape-sequences)

**Comment by a-wakeel** [comment]
The warning is not on python code it is on a Raw SQL. Are you sure about that? Should i post an example sql?

**Comment by asottile** [comment]
I'm 100% positive, yes.  you've got a string literal with an invalid escape sequence in it.

**Comment by FichteFoll** [comment]
Python started warning about invalid escape sequences in 3.7, if memory serves me right. They will become a syntax error in the future, so you better check whether you are escaping your string correctly or should be using a raw string.
