### ISSUE TITLE
W503 reported only after E203 is ignored

### ISSUE THREAD

**Issue by fuglede** [PyCQA/pycodestyle#965]
Consider the following simple file, let's call it `test.py`:

```py
a = (
    2
    + 2
)
```

That is, something one might expect to find after running `black`. Here, `pycodestyle test.py` reports no errors. Now, ignore E203 (which is also [common in the context of black](https://github.com/PyCQA/pycodestyle/issues/373)), and we get the following output:

```
$ pycodestyle test.py --ignore E203
test.py:3:5: W503 line break before binary operator
```

This is on pycodestyle 2.6.0.

**Comment by asottile** [comment]
hopefully this part of the docs helps explain what you're seeing: https://github.com/PyCQA/pycodestyle/blame/a1b1f7c795ace4c186fd76ec6df994deb716cea8/docs/intro.rst#L434-L435

if you're using `flake8` instead I'd suggest `extend-ignore` which preserves the default ignore list

**Comment by fuglede** [comment]
Yep, indeed it does; thanks!
