### ISSUE TITLE
Windows pathnames causing test failures

### ISSUE THREAD

**Issue by JPeterMugaas** [PyCQA/pycodestyle#966]
I was building pycodestyle on Windows using a special version of Python for MINGW64 using GCC.  The build and many tests were successful.  However, there were two tests that failed.  These two tests fail because the Windows path filename conventions are TOTALLY different than in Unix-based Operating systems such as Linux, OS/X, or FreeBSD.  In Windows, you have a drive letter followed by a ":" and then a fully qualified path/filename.  

pycodestyle-2.6.0/testsuite/test_util.py - normalize_paths does NOT work as you would think.  '/foo/bar,baz/../bat' does NOT resolve to '/foo/bar', cwd + '/bat'] and I would argue that it shouldn't given the semantics I described for a FQN in Windows.  My arguement is that you have a drive letter, ":", maybe a prefix path (depending on Python distribution" and your path such as "foo/bar" or rather "\foo\bar\bat".

The fix I made was this diff.
```diff
--- pycodestyle-2.6.0/testsuite/test_util.py.orig       2020-05-11 15:55:35.000000000 -0400
+++ pycodestyle-2.6.0/testsuite/test_util.py    2020-11-03 06:52:37.417451400 -0500
@@ -17,7 +17,8 @@ class UtilTestCase(unittest.TestCase):
         self.assertEqual(normalize_paths('foo'), ['foo'])
         self.assertEqual(normalize_paths('foo,bar'), ['foo', 'bar'])
         self.assertEqual(normalize_paths('foo,  bar  '), ['foo', 'bar'])
-        self.assertEqual(normalize_paths('/foo/bar,baz/../bat'),
-                         ['/foo/bar', cwd + '/bat'])
+        if (os.name != 'nt') and ('GCC' not in sys.version):
+            self.assertEqual(normalize_paths('/foo/bar,baz/../bat'),
+                             ['/foo/bar', cwd + '/bat'])
         self.assertEqual(normalize_paths(".pyc,\n   build/*"),
                          ['.pyc', cwd + '/build/*'])
```

The second test failure is in pycodestyle-2.6.0/testsuite/test_shell.py.

That causes an error about line.split(':') expecting 4 values instead of 3 values.  The reason is that the standard output of a previous will contain a ":" as part of the fully-qualified File name and that be required for test processing to open the filename mentioned.

I fixed this with something like:

```diff
--- pycodestyle-2.6.0/testsuite/test_shell.py.orig      2020-11-03 07:41:08.380045000 -0500
+++ pycodestyle-2.6.0/testsuite/test_shell.py   2020-11-03 07:48:14.387615800 -0500
@@ -79,7 +79,10 @@ class ShellTestCase(unittest.TestCase):
         self.assertFalse(stderr)
         self.assertEqual(len(stdout), 24)
         for line, num, col in zip(stdout, (3, 6, 6, 9, 12), (3, 6, 6, 1, 5)):
-            path, x, y, msg = line.split(':')
+            if (os.name == 'nt') and ('GCC' in sys.version):
+                path, x, y, msg = line.rsplit(':', 3)
+            else:
+                path, x, y, msg = line.split(':')
             self.assertTrue(path.endswith(E11))
             self.assertEqual(x, str(num))
             self.assertEqual(y, str(col))

```

I don't know what is in the Trunk at the moment and this is specific to the special Python version I'm using.  I am please to report that with the patches, I described, the tests do run in Windows in the MSYS2 environment using the MINGW64 version of Python and I suspect that this could also effect other Python versions for Windows so I suggest that you incorporate something similar.

TIA.

**Comment by asottile** [comment]
while I don't agree with your patch, it is correct that these tests don't pass on windows (the actual functionality is correct, those particular tests are just broken)

what I'd suggest instead: `os.path.realpath` to solve the first one, and you probably just use `rstrip` everywhere independent of the OS for the second one

**Comment by JPeterMugaas** [comment]
Alright, os.realpath does work for the first item.

The second one is more difficult.  The big issue with your split code is this:


======================================================================
ERROR: test_check_simple (test_shell.ShellTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/msys64/home/jpmugaas/exp/mingw-w64-python-pycodestyle/src/python-build-x86_64/testsuite/test_shell.py", line 82, in test_check_simple
    path, x, y, msg = line.split(':')
ValueError: too many values to unpack (expected 4)

----------------------------------------------------------------------
Ran 53 tests in 3.828s

FAILED (errors=1)

===
The problem is that you are parsing output such as:

D:\msys64\home\jpmugaas\exp\mingw-w64-python-pycodestyle\src\python-build-x86_64/pycodestyle.py:125:35: W504 line break after binary operator

That will output four values in split(":") instead of three like you expect.  The first string would be "D" because the second character is a ":"  and in Windows, that ":" is a special character that separates the drive letter from a directory or file name that would ultimately be passed to something in one of your tests to a open a file.  

I have attached the two patches I made for your review.

[0002-test-rsplit.patch.txt](https://github.com/PyCQA/pycodestyle/files/5488389/0002-test-rsplit.patch.txt)
[0001-fix-mingw-test-path.patch.txt](https://github.com/PyCQA/pycodestyle/files/5488390/0001-fix-mingw-test-path.patch.txt)

**Comment by asottile** [comment]
please use triple backticks (`) to surround code blocks so I don't have to keep editing your messages :)

I completely understand what you're saying, but my suggestion of using `.rstrip(':', 3)` in both cases works perfectly

**Comment by asottile** [comment]
please don't attach patches as well, send pull requests

**Comment by JPeterMugaas** [comment]
I think rtrim is not needed to address the parsing issue I described in Windows.  That would only remove whitespace from the end of the line.  Now if pycodestyle needs to do this in it's code, that's a separate thing than I described.  If I'm missing something, please follow up.

[0002-test-rsplit.patch.txt](https://github.com/PyCQA/pycodestyle/files/5489086/0002-test-rsplit.patch.txt)

**Comment by asottile** [comment]
ah I mispoke, I meant rsplit

**Comment by asottile** [comment]
but yeah please don't attach patches we can't accept changes that way -- [make a pull request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)

**Comment by JPeterMugaas** [comment]
Okay.  I think we now are on the same page with everything.  I have made a pull request based on your comments at:

https://github.com/PyCQA/pycodestyle/pull/967

If I missed something, please let me know.  Otherwise, I hope the best on a Unix-like OS since you wanted to remove the OS-specific "if" in my code.

Anyway, I suspect that something similar is happening to other tests in other projects.

**Comment by asottile** [comment]
via #967
