### ISSUE TITLE
W504: Possible to have "and" and "or" on line alone?

### ISSUE THREAD

**Issue by mkleehammer** [PyCQA/pycodestyle#969]
When some conditionals are long, it seems reasonable to use something like this:

```python
flag = (
    long_predicate(one, two, three, four)
    and
    another_long_predicate(five, six, seven)
)
```

This is getting flagged by W504 line break after binary operator.  Is it possible to configure this globally so the example above is allowed without disabling W504 completely?  Can this style be made an exception to W504?

**Comment by asottile** [comment]
please search the tracker, I've taken the time to prefix each issue with the error code so you can easily find duplicates -- in your case #815
