### ISSUE TITLE
W503 and W504 confilict when using Microsoft Visual Studio Code

### ISSUE THREAD

**Issue by jgossage** [PyCQA/pycodestyle#971]
My environment is:
```
Microsoft Visual Code Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20270
```
The following problem only occurs when running `pycodestyle` within `Visual Studio Code`. `Pycodestyle` works correctly in a standalone command-line environment. I have the following code:

```
df = {}
x = not ('abc' in df and
         'def' in df)
```

This gives a W504 error. If I change the code to the following I get a W503 error.

```
df = {}
x = not ('abc' in df'
         and 'def' in df)
```

There appears to be no way to write this code without getting a `pycodestyle` generated error when running on
`Visual Studio Code`. Is this a bug in `pycodestyle`, a bug in `Visual Studio Code` when interfacing to `pycodestyle` or my bad use of Python? The code also works properly when run with raw `Python`.

**Comment by asottile** [comment]
You'll want to show your configuration -- my guess is you're using `--ignore` and in that case you're probably not selecting one of the two.  Those errors are conflicting but disabled by default

Note that if you're using flake8 you'll want to use `extend-ignore` as it preserves the default ignored state

**Comment by jgossage** [comment]
I am using Visual Studio Code with the environment that it establishes. In any case, if both warnings are enabled, should it be possible to get a situation where the code is never acceptable?

**Comment by asottile** [comment]
Can you share your setup.cfg or your tox.ini -- You must have some sort of configuration that's overriding the default because those codes are disabled by default

**Comment by jgossage** [comment]
I did not create either configuration file, the runtime environment for `pycodestyle` was established by `Visual Studio Code`. In any case, why is one of the errors always produced? These are useful warnings when they don't conflict.

**Comment by asottile** [comment]
Additionally if you're confused, I'd suggest searching W504 / W503 in the issue tracker -- there's many duplicates there

But if you have no configuration, I'd suggest you report the issue to vs code because the problem is not here

**Comment by sigmavirus24** [comment]
>  In any case, if both warnings are enabled, should it be possible to get a situation where the code is never acceptable?

Yes it should be given that the style guide this tool implements has flip-flop'd often and developers tend to know well enough to pick one or the other.
