### ISSUE TITLE
E704 on stubs

### ISSUE THREAD

**Issue by Dreamsorcerer** [PyCQA/pycodestyle#973]
It would be nice to be able to ignore E704 with typing stubs, which essentially have no function body.

e.g.
```
class _VehicleTaskState(Protocol):
    def __call__(self) -> Awaitable["_VehicleTaskState"]: ...
```

The `...` cause E704 as it's on the same line. For typing stubs, this seems to be the preferred approach for formatting (e.g. look at the typeshed repo).

**Comment by asottile** [comment]
E704 is disabled by default for this reason -- you have to be opting into it to receive an error on that line

**Comment by Dreamsorcerer** [comment]
Indeed, I'm just proposing that it gets special cased for typing stubs.
