### ISSUE TITLE
Validate CamelCase

### ISSUE THREAD

**Issue by TiedtTech** [PyCQA/pycodestyle#984]
How do I use the package and validate CamelCase.

Example in the source below. In PyCharm he says the line is wrong.

```
class SumValues:
    pass


class sum_two_values:
    pass


```
However when doing in the terminal

`pycodestyle main.py`

returns no error
What am I doing wrong?

**Comment by asottile** [comment]
you're looking for [pep8-naming](https://github.com/pycqa/pep8-naming)
