### ISSUE TITLE
E127: error in (what I believe to be) compliant code. 

### ISSUE THREAD

**Issue by ngodber** [PyCQA/pycodestyle#988]
Hi,

Apologies if this has been raised. Did a fair amount of googling and cannot find an issue that covers this exact situation.

So I'm receiving an error on below:

![image](https://user-images.githubusercontent.com/11834846/113530957-c42c2980-960a-11eb-95bf-cd9a07bdc902.png)

Adjusting as follows 
![image](https://user-images.githubusercontent.com/11834846/113530974-d7d79000-960a-11eb-93ca-7cc7431d7547.png)
causes the error to go away but this appears incorrect to me though I'm not a pep8 expert by any means.

There are multiple threads around covering this issue:

https://youtrack.jetbrains.com/issue/PY-24792

https://youtrack.jetbrains.com/issue/PY-30327

Cheers

**Comment by asottile** [comment]
please don't show screenshots of text it is (1) inaccessible I can't view it in my own contrast / font size settings (2) unsearchable (3) uncopyable

I also cannot reproduce your findings, be sure to include your version information and check to make sure you're running the latest version

**Comment by asottile** [comment]
make sure to also include any relevant configuration

**Comment by ngodber** [comment]
Hi, apologies. Thanks for the fast reply. Here is a minimal code snap shot that reproduces the notification in my env. In terms of configuration, I'm running with defaults under pycharm. I don't know how to access what, if any, configurations are being set by pycharm when passing to pycodestyle. @east825 may be able to provide this information. Obviously below example doesn't actually require line continuation but the situation typically occurs when multiplying results of method calls. Closest pep documentation I can find regarding this is (https://www.python.org/dev/peps/pep-0008/#id20)/ 

`def test():
    a_test_variable = 1
    b_test_variable = 2
    c_test_variable = a_test_variable * \
                      b_test_variable`

**Comment by asottile** [comment]
[on github, surround code blocks with three backticks on their own lines](https://youtu.be/1UodxuXj5Ao?list=PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY)

**Comment by ngodber** [comment]
as an aside, same snippet opened in vscode doesnt register the non compliance.

**Comment by asottile** [comment]
it seems to me like the error in that example is correct.  this is what pycodestyle wants that to be:

```python
def test():
    a_test_variable = 1
    b_test_variable = 2
    c_test_variable = a_test_variable * \
        b_test_variable
```

though I find both of those ugly, as does the PEP:

> The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.

this is much better and avoids the problem entirely:

```python
def test():
    a_test_variable = 1
    b_test_variable = 2
    c_test_variable = (
        a_test_variable *
        b_test_variable
    )
```

or depending on whether your code prefers W504 vs W503:

```python
def test():
    a_test_variable = 1
    b_test_variable = 2
    c_test_variable = (
        a_test_variable
        * b_test_variable
    )
```

**Comment by ngodber** [comment]
Thanks for the feedback. I wasn't aware for the recommendation preferring additional parenthesis over backslash.
